"use client";
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {stations} from './content';

export default function Classroom({onSelect,onFallback,unlocked,band=false}:{onSelect:(station:string,item?:string)=>void;onFallback:()=>void;unlocked:boolean;band?:boolean}) {
 const host=useRef<HTMLDivElement>(null);const move=useRef<(x:number,z:number)=>void>(()=>{});const reset=useRef<()=>void>(()=>{});const [hover,setHover]=useState('Selecciona una persona o un objeto');const selection=useRef(onSelect);
 useEffect(()=>{selection.current=onSelect},[onSelect]);
 useEffect(()=>{
  const element=host.current!;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch{onFallback();return;}
  renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#d8e9ee');element.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D classroom. Drag to look, use movement controls, or choose a station from the accessible list.');renderer.domElement.tabIndex=0;
  const scene=new THREE.Scene();scene.background=new THREE.Color('#d8e9ee');const camera=new THREE.PerspectiveCamera(48,1,.1,100);camera.position.set(8,7,10);
  const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,0);controls.enableDamping=!window.matchMedia('(prefers-reduced-motion: reduce)').matches;controls.minDistance=1;controls.maxDistance=20;controls.maxPolarAngle=Math.PI*.49;controls.update();
  scene.add(new THREE.HemisphereLight(0xffffff,0x475f69,2.6));const sun=new THREE.DirectionalLight(0xfff5db,3);sun.position.set(-5,10,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;scene.add(sun);
  const materials:THREE.Material[]=[];const geometries:THREE.BufferGeometry[]=[];const textures:THREE.Texture[]=[];const selectable:THREE.Object3D[]=[];
  function mesh(geometry:THREE.BufferGeometry,color:string,x:number,y:number,z:number,parent:THREE.Object3D=scene){geometries.push(geometry);const m=new THREE.MeshStandardMaterial({color,roughness:.8});materials.push(m);const o=new THREE.Mesh(geometry,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
  const box=(w:number,h:number,d:number,c:string,x:number,y:number,z:number,parent:THREE.Object3D=scene)=>mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,parent);
  function tag(o:THREE.Object3D,station:string,item?:string){o.userData={station,item};selectable.push(o);return o;}
  function label(text:string,x:number,y:number,z:number,station:string){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle='#173342';ctx.fillRect(0,0,512,128);ctx.fillStyle='white';ctx.font='bold 38px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,79);const texture=new THREE.CanvasTexture(c);textures.push(texture);const material=new THREE.SpriteMaterial({map:texture});materials.push(material);const sprite=new THREE.Sprite(material);sprite.position.set(x,y,z);sprite.scale.set(2.3,.57,1);scene.add(sprite);tag(sprite,station);}
  box(11,.2,10,'#bbccc8',0,-.1,0);for(let i=-5;i<6;i++)box(.025,.01,10,'#9fb4b2',i,.01,0);for(let i=-4;i<5;i++)box(11,.01,.025,'#9fb4b2',0,.012,i);
  box(11,4,.18,'#edf0df',0,2,-5);box(.18,4,10,'#f3e2b5',-5.5,2,0);box(11,.2,.2,'#d4966b',0,.35,-4.85);
  for(const z of [-3,0,3]){tag(box(.05,1.5,1.7,'#7fc1dd',-5.38,2.35,z),'supplies','ventana');box(.08,.06,1.9,'#faf8ea',-5.32,2.35,z);box(.08,1.65,.05,'#faf8ea',-5.32,2.35,z);}
  tag(box(4,1.7,.12,'#225647',0,2.2,-4.8),'doctor','pizarra');box(4.2,.1,.24,'#dbbb83',0,1.3,-4.75);label(band?'¡Somos músicos!':'Mis clases y mis compañeros',0,3.35,-4.6,'doctor');
  tag(box(.9,2.8,.13,unlocked?'#e5a63e':'#718595',-4,1.4,-4.78),'band','puerta');label(unlocked?'Sala de música':'Música · 4 misiones',-4,3.05,-4.5,'band');
  const clock=tag(mesh(new THREE.CylinderGeometry(.37,.37,.08,32),'#faf8ea',3,3,-4.8),'supplies','reloj');clock.rotation.x=Math.PI/2;box(.025,.25,.02,'#173342',3,3.11,-4.73);box(.22,.025,.02,'#173342',3.1,3,-4.72);
  function desk(x:number,z:number,color='#dca873'){tag(box(1.65,.13,.9,color,x,1,z),'supplies','escritorio');for(const dx of [-.65,.65])for(const dz of [-.32,.32])box(.08,.95,.08,'#637e87',x+dx,.5,z+dz);tag(box(.65,.12,.62,'#e6b744',x,.56,z+1),'supplies','silla');box(.65,.62,.1,'#e6b744',x,.94,z+1.27);for(const dx of [-.25,.25])box(.07,.55,.07,'#637e87',x+dx,.25,z+1);}
  for(const x of [-2.3,0,2.3])for(const z of [0,2.7])desk(x,z);desk(-3,-3,'#ecbba0');
  function person(name:string,color:string,x:number,z:number,station:string){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);tag(mesh(new THREE.CapsuleGeometry(.23,.43,4,10),color,0,1.05,0,g),station);tag(mesh(new THREE.SphereGeometry(.23,18,12),'#b97e57',0,1.62,0,g),station);mesh(new THREE.SphereGeometry(.237,18,12),'#302c2b',0,1.69,-.035,g).scale.set(1,.65,1);for(const dx of [-.12,.12])box(.13,.55,.15,'#314861',dx,.35,0,g);for(const dx of [-.31,.31])box(.13,.6,.15,color,dx,.92,0,g);label(name,x,2.3,z,station);}
  if(!band){person('Sra. Abarca','#f37053',-3,-3,'teacher');person('Mateo','#2faaa1',3,1,'mateo');person('Fernando','#d15f8d',1,-1,'group');person('Ana','#d15f8d',2.4,-1.3,'group');person('Sofía','#835ec0',3.5,-1.3,'group');person('Victoria','#4c91aa',4,2,'group');}
  else {person('Directora','#f37053',0,-2.8,'band');person('Mateo','#2faaa1',3,1,'band');const drum=tag(mesh(new THREE.CylinderGeometry(.6,.6,.7,28),'#d96348',-2,.7,-2),'band');box(1.6,.14,.75,'#173342',1,1.2,-2);for(let i=0;i<12;i++)box(.12,.02,.65,'#f6f0d5',.27+i*.12,1.29,-2);mesh(new THREE.CylinderGeometry(.55,.55,.035,24),'#e4b83d',-2,1.9,-2.7);void drum;}
  tag(box(.5,.65,.25,'#7089d8',0,1.38,2.7),'backpack','mochila');mesh(new THREE.TorusGeometry(.14,.025,6,16),'#4256a3',0,1.75,2.7);label('La mochila',0,2.25,2.7,'backpack');
  tag(box(.4,.06,.55,'#f37053',-2.3,1.11,0),'supplies','libro');tag(box(.36,.04,.48,'#f6f3dc',-2.3,1.15,0),'supplies','cuaderno');const pencil=tag(mesh(new THREE.CylinderGeometry(.022,.022,.5,6),'#e9ad30',-1.9,1.13,0),'supplies','lapiz');pencil.rotation.z=Math.PI/2;tag(box(.16,.08,.1,'#ea998c',-2.5,1.14,.25),'supplies','borrador');label('Los útiles',-2.3,1.9,0,'supplies');
  tag(box(1.6,1.7,.08,'#faf5df',4,2.1,-4.8),'schedule','horario');label('El horario',4,3.2,-4.5,'schedule');
  tag(box(.65,.9,.65,'#4d727f',-4.5,.45,3.6),'supplies','papelera');tag(box(1.2,.12,.9,'#b37d59',4,1,3),'supplies','mesa');label('Mesa de arte',4,1.9,3,'supplies');tag(box(.3,.02,.4,'#f6f0d5',4,1.09,3),'supplies','papel');
  const raycaster=new THREE.Raycaster();const pointer=new THREE.Vector2();let downX=0,downY=0;const hit=(event:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(selectable,false)[0]?.object;};
  const down=(e:PointerEvent)=>{downX=e.clientX;downY=e.clientY};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-downX,e.clientY-downY)>7)return;const o=hit(e);if(o)selection.current(o.userData.station,o.userData.item);};const over=(e:PointerEvent)=>{const o=hit(e);renderer.domElement.style.cursor=o?'pointer':'grab';setHover(o?stations.find(s=>s.id===o.userData.station)?.name??'Explora':'Selecciona una persona o un objeto');};
  renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointermove',over);
  const navigate=(x:number,z:number)=>{const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0));const delta=right.multiplyScalar(x*.6).add(forward.multiplyScalar(z*.6));if(Math.abs(controls.target.x+delta.x)>5||Math.abs(controls.target.z+delta.z)>4.5)return;camera.position.add(delta);controls.target.add(delta);controls.update();};move.current=navigate;reset.current=()=>{camera.position.set(8,7,10);controls.target.set(0,1,0);controls.update();};
  const key=(e:KeyboardEvent)=>{if(!['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();navigate(['d','ArrowRight'].includes(e.key)?1:['a','ArrowLeft'].includes(e.key)?-1:0,['w','ArrowUp'].includes(e.key)?1:['s','ArrowDown'].includes(e.key)?-1:0);};renderer.domElement.addEventListener('keydown',key);
  const resize=new ResizeObserver(()=>{const w=element.clientWidth,h=element.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe(element);let frame=0;const render=()=>{controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(render)};render();
  const lost=(e:Event)=>{e.preventDefault();onFallback();};renderer.domElement.addEventListener('webglcontextlost',lost);
  return ()=>{cancelAnimationFrame(frame);resize.disconnect();controls.dispose();renderer.dispose();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.domElement.remove();};
 },[unlocked,band,onFallback]);
 return <div className="room-wrap"><div ref={host} className="room-canvas" data-testid="classroom"/><div className="room-caption" aria-live="polite">{hover}</div><div className="camera-controls" aria-label="Move around the classroom"><button onClick={()=>move.current(0,1)} aria-label="Move forward">Avanzar</button><button onClick={()=>move.current(-1,0)} aria-label="Move left">Izquierda</button><button onClick={()=>move.current(1,0)} aria-label="Move right">Derecha</button><button onClick={()=>move.current(0,-1)} aria-label="Move backward">Atrás</button><button onClick={()=>reset.current()}>Vista general</button></div><p className="camera-help">Arrastra para mirar · Drag to look · WASD / arrow keys when the scene has focus</p></div>;
}
