export type Skill = 'self' | 'pronouns' | 'ser' | 'perspective' | 'objects' | 'hay' | 'articles' | 'likes' | 'adjectives' | 'uses';
export const skillLabels: Record<Skill,string> = {self:'Presentarme',pronouns:'Pronombres',ser:'SER',perspective:'¿Quién habla?',objects:'Útiles',hay:'Hay',articles:'Artículos',likes:'Gustos',adjectives:'Adjetivos',uses:'Usos de SER'};
export type Option = {id:string; text:string};
export type Question = {id:string; skill:Skill; prompt:string; help:string; answers:string[]; options?:Option[]; model:string; explanation:string; source:string; strictAccent?:boolean; visual?:'backpack'|'pencil'|'group'; speaker?:string; listeners?:string[]; about?:string[]; hint:string; variant?:boolean};
export const pronouns = [
 ['yo','I','soy'],['tú','you · informal singular','eres'],['usted','you · formal singular','es'],['él','he','es'],['ella','she','es'],['nosotros','we · masculine or mixed','somos'],['nosotras','we · all female','somos'],['vosotros / vosotras','you · informal plural, mainly in Spain','sois'],['ustedes','you · plural','son'],['ellos','they · masculine or mixed','son'],['ellas','they · all female','son']
];
export const vocabulary = [
 ['escuela','la escuela / el colegio','school','Voy a la escuela.'],['estudiante','el estudiante / la estudiante','student','Soy estudiante.'],['profesor','el profesor / la profesora; el maestro / la maestra','teacher','Ella es profesora.'],['utiles','los útiles','school supplies','Uso los útiles en la clase.'],
 ['borrador','el borrador','eraser','Uso un borrador para corregir un error de lápiz.'],['calculadora','la calculadora','calculator','Uso la calculadora en matemáticas.'],['cinta','la cinta','tape','Uso la cinta con el papel.'],['cuaderno','el cuaderno','notebook','Escribo en un cuaderno.'],['escritorio','el escritorio','desk','El libro está en el escritorio.'],['estuche','el estuche','pencil pouch','Hay lápices en el estuche.'],['goma','la goma','glue on this class list','Uso la goma para pegar papel.'],['lapiz','el lápiz','pencil','Uso un lápiz para escribir.'],['colores','los lápices de colores','colored pencils','Uso lápices de colores en arte.'],['libro','el libro','book','Hay un libro en la mochila.'],['mapa','el mapa','map','El mapa es grande.'],['marcador','el marcador','marker','Uso un marcador en la pizarra.'],['mesa','la mesa','table','Hay una mochila en la mesa.'],['mochila','la mochila','backpack','Hay dos lápices en la mochila.'],['papel','el papel','paper','Uso papel en arte.'],['papelera','la papelera','wastebasket','La papelera está junto a la puerta.'],['pizarra','la pizarra','board','La pizarra es verde.'],['boligrafo','la pluma / el bolígrafo','pen','Uso un bolígrafo para escribir.'],['puerta','la puerta','door','La puerta es azul.'],['regla','la regla','ruler','Uso una regla para medir.'],['reloj','el reloj','clock','Son las dos.'],['silla','la silla','chair','La silla es amarilla.'],['tijeras','las tijeras','scissors','Uso las tijeras para cortar papel.'],['ventana','la ventana','window','La ventana es grande.'],['clase','la clase','class','La clase es divertida.'],['curso','el curso','course','El curso es interesante.'],['examen','el examen','test','Tengo un examen.'],['horario','el horario','schedule','Este es mi horario.'],['prueba','la prueba','quiz','Tengo una prueba.'],['semestre','el semestre','semester','Este semestre tengo español.'],['tarea','la tarea','homework','La tarea es fácil.'],['almuerzo','el almuerzo','lunch','Tengo el almuerzo a las doce.'],['carpeta','la carpeta','folder · exercise enrichment','Uso una carpeta para guardar mis apuntes.']
];
export const subjects = ['el arte','las ciencias','la computación','la educación física','el español','los estudios sociales','el inglés','el lenguaje','las matemáticas','la música'];
export const adjectives = ['trabajador / trabajadora — hardworking','perezoso / perezosa; flojo / floja — lazy (fictional examples only)','aburrido / aburrida — boring','divertido / divertida — fun','organizado / organizada — organized','desordenado / desordenada — messy','artístico / artística — artistic','atlético / atlética — athletic','chistoso / chistosa — funny','fácil — easy','difícil — difficult','exigente — demanding','estudioso / estudiosa — studious','responsable — responsible','estricto / estricta — strict','simpático / simpática — nice'];
export const doctor = [
 ['D','Descripción','La mochila es azul. / La mesa es de madera.','Description, including material.'],['O','Ocupación','Ella es profesora.','Occupation/profession. The chart also lists ideology; no personal disclosure needed.'],['C','Características','Mateo es simpático.','Characteristics can overlap with description.'],['T','Tiempo','Es la una. / Son las dos.','Time, day and date. In our fictional schedule: Hoy es martes.'],['O','Origen','Sofía es de México.','Origin of a fictional character.'],['R','Relaciones','Fernando y yo somos amigos.','Personal relationships.'],['+','Identificación','Es un cuaderno.','Identification.'],['+','Eventos','El concierto es en la escuela el viernes.','Event location and time.'],['+','Posesión','El libro es de Ana.','Possession. SER is not simply a rule about permanence.']
];
const A='Class vocabulary list · new practice'; const B='Pronouns & SER chart · new practice'; const C='DOCTOR chart · new practice';
const englishPrompts:Record<string,string>={tu:'Complete the question asking whether you are a student.',usted:'Tell the teacher formally: You are a teacher.',ella:'Talk about the teacher: She is a teacher.','mateo-response':'Mateo asks: Are you a student? Answer for yourself.',fernando:'Yusuf speaks about Fernando and himself: Fernando and I are students.',ellas:'Talk ABOUT Ana and Sofía. Choose the pronoun.',ellos:'Talk ABOUT Mateo and Ana. Choose the pronoun.',nosotras:'Sofía includes herself and Ana: We are friends.',sois:'Complete the informal plural you sentence used mainly in Spain.','el-accent':'Choose the pronoun meaning he.','tu-accent':'Choose the pronoun meaning you.',measure:'I need to measure this line. What do I use?',cut:'I need to cut paper. What do I use?',folder:'Carpeta means folder. What holds my notes together?',table:'What does la mesa mean?',fifteen:'There are quince mochilas. How many backpacks?','plural-hay':'Complete a sentence about two pencils in another practice backpack.',pencils:'Write the plural of un lápiz.',backpacks:'Write the plural of la mochila.',map:'Choose the singular definite article for mapa.','mochila-article':'Choose the singular definite article for mochila.',music:'Complete: I like music.',math:'Complete: I like mathematics.',dislike:'Say: I do not like music.',schedule:'The fictional schedule shows music. Complete: I have music class.',fun:'The classes are ___. Use the word for fun.',organized:'Ana and Sofía are ___ students. Use the word for organized.',students:'Complete: They are students.',occupation:'She is a teacher. Choose the use of SER.',relationship:'We are friends. Choose the use of SER.',origin:'Sofía is from Mexico. Choose the use of SER.',time:'It is two o’clock. Choose the use of SER.',write:'In an ordinary classroom, I can write in a notebook. True or false?','eraser-write':'To write words, I use an eraser. True or false?','band-self':'Are you a musician? Answer for yourself.','band-group':'The director addresses you and Mateo: Are you musicians? Answer for your group.'};
function q(id:string,skill:Skill,prompt:string,answers:string[],model:string,explanation:string,options?:string[], extra:Partial<Question>={}):Question {
 return {id,skill,prompt,help:englishPrompts[id]??'Respond to the Spanish prompt using the visible scene.',answers,model,explanation,source:skill==='uses'?C:['self','pronouns','ser','perspective'].includes(skill)?B:A,hint:model,options:options?.map(text=>({id:text,text})),...extra};
}
export const questions:Question[] = [
 q('self-intro','self','Hola, soy la profesora Abarca. ¿Quién eres?',['Soy Yusuf','Yo soy Yusuf'],'Soy Yusuf.','Introduce yourself with (yo) soy. The subject pronoun can be omitted.',undefined,{speaker:'Sra. Abarca',listeners:['Yusuf'],help:'Hello, I am Ms. Abarca. Who are you?'}),
 q('self-pronoun','self','¿Qué pronombre usas para hablar de ti?',['yo'],'yo','Talking about yourself uses yo.',['yo','tú','él'],{speaker:'Yusuf',about:['Yusuf'],help:'Which pronoun do you use to talk about yourself?'}),
 q('tu','ser','¿___ tú estudiante?',['eres'],'¿Eres tú estudiante?','Tú takes eres. You answer: Sí, soy estudiante.',undefined,{speaker:'Mateo',listeners:['Yusuf']}),
 q('usted','ser','Usted ___ profesora.',['es'],'Usted es profesora.','Formal singular usted takes es.',undefined,{speaker:'Yusuf',listeners:['Sra. Abarca']}),
 q('ella','ser','La profesora Abarca: ella ___ profesora.',['es'],'Ella es profesora.','Talking about one woman uses ella es.',undefined,{speaker:'Yusuf',about:['Sra. Abarca']}),
 q('mateo-response','self','Mateo: ¿Tú eres estudiante?',['Sí, soy estudiante','Soy estudiante','Sí, yo soy estudiante','Yo soy estudiante'],'Sí, soy estudiante.','Mateo addresses you with tú; your response uses yo (soy).',undefined,{speaker:'Mateo',listeners:['Yusuf']}),
 q('fernando','perspective','Yusuf habla: Fernando y yo ___ estudiantes.',['somos'],'Fernando y yo somos estudiantes.','A group including the speaker uses nosotros somos.',undefined,{speaker:'Yusuf',about:['Yusuf','Fernando'],visual:'group'}),
 q('victoria','pronouns','Hablas A Victoria y a otra persona que tratas de usted. ¿Qué pronombre?',['ustedes'],'ustedes','Addressing two people together uses ustedes.',['ustedes','ellos','nosotros'],{speaker:'Yusuf',listeners:['Victoria','Sra. Abarca'],visual:'group',help:'You address Victoria and a person you address formally, together.'}),
 q('ellas','pronouns','Hablas SOBRE Ana y Sofía. ¿Qué pronombre?',['ellas'],'ellas','Talking about Ana and Sofía uses ellas; talking to them uses ustedes.',['ellas','ustedes','nosotras'],{speaker:'Yusuf',about:['Ana','Sofía'],visual:'group'}),
 q('ellos','pronouns','Hablas SOBRE Mateo y Ana. ¿Qué pronombre?',['ellos'],'ellos','This beginner convention uses ellos for a mixed group.',['ellos','ellas','ustedes'],{speaker:'Yusuf',about:['Mateo','Ana'],visual:'group'}),
 q('nosotras','pronouns','Sofía habla de sí misma y Ana: ___ somos amigas.',['nosotras'],'Nosotras somos amigas.','Sofía includes herself in an all-female group.',undefined,{speaker:'Sofía',about:['Sofía','Ana'],visual:'group'}),
 q('sois','ser','Extensión de España: Vosotros ___ estudiantes.',['sois'],'Vosotros sois estudiantes.','Vosotros and vosotras take sois; informal plural, mainly in Spain.'),
 q('el-accent','pronouns','Selecciona el pronombre que significa “he”.',['él'],'él','Él means he; el is the article the. The accent changes the meaning.',['el','él'],{strictAccent:true}),
 q('tu-accent','pronouns','Selecciona el pronombre que significa “you”.',['tú'],'tú','Tú is you; tu means your.',['tu','tú'],{strictAccent:true}),
 q('erase','objects','Hay un error de lápiz. ¿Qué usas para borrarlo?',['el borrador'],'Uso un borrador.','An eraser corrects a pencil mistake.',['el borrador','el bolígrafo','la regla'],{visual:'pencil',help:'There is a pencil mistake. What do you use to erase it?'}),
 q('measure','objects','Necesito medir esta línea. ¿Qué uso?',['la regla'],'Uso una regla.','A ruler measures a line.',['la regla','la goma','el libro']),
 q('cut','objects','Necesito cortar papel. ¿Qué uso?',['las tijeras'],'Uso las tijeras.','Scissors cut paper.',['las tijeras','el borrador','la cinta']),
 q('folder','objects','La carpeta = folder (palabra extra). ¿Qué uso para guardar mis apuntes juntos?',['la carpeta'],'Uso una carpeta.','Folder is enrichment from the exercise, beyond the attached class list.',['la carpeta','la ventana','el reloj']),
 q('table','objects','La mesa significa…',['table'],'table','La mesa is table; el escritorio is desk.',['table','desk','backpack']),
 q('fifteen','hay','Hay quince mochilas. ¿Cuántas mochilas hay?',['fifteen backpacks'],'fifteen backpacks','Quince is fifteen; mochilas are backpacks.',['fifteen backpacks','fifteen desks','five backpacks']),
 q('plural-hay','hay','En otra mochila de práctica, ___ dos lápices.',['hay'],'Hay dos lápices en esa mochila de práctica.','Hay stays the same for one item or several items.'),
 q('pencils','articles','Escribe el plural de un lápiz.',['unos lápices'],'unos lápices','Un becomes unos; lápiz becomes lápices.'),
 q('backpacks','articles','Escribe el plural de la mochila.',['las mochilas'],'las mochilas','La becomes las; mochila becomes mochilas.'),
 q('map','articles','Elige el artículo definido: ___ mapa.',['el'],'el mapa','Mapa is masculine even though it ends in -a.',['el','la','los']),
 q('mochila-article','articles','Elige el artículo definido singular: ___ mochila.',['la'],'la mochila','Mochila is feminine and singular.',['la','el','las']),
 q('music','likes','Me ___ la música.',['gusta'],'Me gusta la música.','La música is singular, so use gusta.'),
 q('math','likes','Me ___ las matemáticas.',['gustan'],'Me gustan las matemáticas.','Las matemáticas is plural, so use gustan.'),
 q('dislike','likes','Expresa “I do not like music”.',['No me gusta la música','A mí no me gusta la música'],'No me gusta la música.','Add no before me gusta. This is a new practice example.'),
 q('schedule','likes','Tu horario muestra música. Completa: Tengo la clase de ___.',['música'],'Tengo la clase de música.','Use the subject shown on the fictional schedule.'),
 q('fun','adjectives','Las clases son ___. (fun)',['divertidas'],'Las clases son divertidas.','Clases is feminine plural, so use divertidas.'),
 q('organized','adjectives','Ana y Sofía son estudiantes ___. (organized)',['organizadas'],'Ana y Sofía son estudiantes organizadas.','An all-female plural group takes organizadas.'),
 q('students','ser','Ellos ___ estudiantes.',['son'],'Ellos son estudiantes.','Ellos, ellas and ustedes take son.'),
 q('occupation','uses','Ella es profesora. ¿Qué uso de SER?',['Ocupación'],'Ocupación','Professora describes her occupation.',['Ocupación','Tiempo','Origen']),
 q('relationship','uses','Somos amigos. ¿Qué uso de SER?',['Relaciones'],'Relaciones','Friends is a personal relationship.',['Relaciones','Tiempo','Origen']),
 q('origin','uses','Sofía es de México. ¿Qué uso de SER?',['Origen'],'Origen','This fictional character’s origin uses SER.',['Origen','Ocupación','Tiempo']),
 q('time','uses','Son las dos. ¿Qué uso de SER?',['Tiempo'],'Tiempo','Clock time uses SER.',['Tiempo','Origen','Relaciones']),
 q('write','objects','En una clase normal, puedo escribir en un cuaderno.',['Cierto'],'Cierto','A notebook is an ordinary writing surface.',['Cierto','Falso']),
 q('eraser-write','objects','Para escribir palabras en papel, uso un borrador.',['Falso'],'Falso','An ordinary eraser removes pencil marks rather than writing words.',['Cierto','Falso']),
 q('band-self','self','¿Eres músico?',['Soy músico','Sí, soy músico','Yo soy músico','Sí, yo soy músico'],'Sí, soy músico.','Músico is music enrichment. Answer for yourself with soy.',undefined,{speaker:'Mateo',listeners:['Yusuf']}),
 q('band-group','perspective','Directora: ¿Ustedes son músicos?',['Sí, somos músicos','Somos músicos','Sí, nosotros somos músicos','Nosotros somos músicos'],'Sí, somos músicos.','The director addresses ustedes; you answer for your group with nosotros somos.',undefined,{speaker:'Directora',listeners:['Yusuf','Mateo'],about:['Yusuf','Mateo'],visual:'group'})
];
export const reviewQuestions:Question[] = [
 q('review-self','self','Sofía te pregunta: ¿Quién eres?',['Soy Yusuf','Yo soy Yusuf'],'Soy Yusuf.','Use soy to introduce yourself.',undefined,{variant:true}),
 q('review-pronoun','pronouns','Hablas A Ana y Sofía. ¿Qué pronombre?',['ustedes'],'ustedes','Talking TO the group uses ustedes, rather than ellas.',['ustedes','ellas','nosotras'],{variant:true,speaker:'Yusuf',listeners:['Ana','Sofía']}),
 q('review-ser','ser','Tú ___ músico.',['eres'],'Tú eres músico.','Tú takes eres.',undefined,{variant:true}),
 q('review-perspective','perspective','Yusuf y Ana responden como grupo: ___ estudiantes.',['Somos','Nosotros somos'],'Somos estudiantes.','A group including the speaker uses somos.',undefined,{variant:true,speaker:'Yusuf',about:['Yusuf','Ana']}),
 q('review-objects','objects','Para escribir una nota con tinta, ¿qué usas?',['el bolígrafo','la pluma'],'Uso un bolígrafo / una pluma.','Both are words for pen on the sheet.',['el bolígrafo','la pluma','el borrador'],{variant:true}),
 q('review-hay','hay','___ una mochila en la mesa.',['hay'],'Hay una mochila en la mesa.','Hay is unchanged for a singular noun.',undefined,{variant:true}),
 q('review-articles','articles','Escribe el plural de el libro.',['los libros'],'los libros','El becomes los for masculine plural.',undefined,{variant:true}),
 q('review-likes','likes','A Mateo le ___ los estudios sociales.',['gustan'],'A Mateo le gustan los estudios sociales.','The thing liked is plural.',undefined,{variant:true}),
 q('review-adjectives','adjectives','Los compañeros son ___. (nice)',['simpáticos'],'Los compañeros son simpáticos.','Companeros is masculine plural.',undefined,{variant:true}),
 q('review-uses','uses','El libro es de Ana. ¿Qué expresa?',['Posesión'],'Posesión','SER with de can show who owns something.',['Posesión','Tiempo','Origen'],{variant:true})
];
export const extraQuestions:Question[]=[
 q('nosotras-ser','ser','Ana y Sofía hablan juntas: Nosotras ___ organizadas.',['somos'],'Nosotras somos organizadas.','Nosotras takes somos.',undefined,{speaker:'Ana',about:['Ana','Sofía']}),
 q('nosotros-guide','perspective','Yusuf incluye a Fernando y a sí mismo. ¿Qué pronombre?',['nosotros'],'nosotros','A mixed group including the speaker uses nosotros.',['nosotros','ellos','ustedes'],{speaker:'Yusuf',about:['Yusuf','Fernando'],visual:'group'})
];
export const targetedQuestions:Question[]=[
 q('target-self','self','Fernando dice: “Soy Fernando”. Ahora preséntate tú.',['Soy Yusuf','Yo soy Yusuf'],'Soy Yusuf.','Introduce yourself using soy.'),
 q('target-pronouns','pronouns','Hablas SOBRE Victoria. ¿Qué pronombre?',['ella'],'ella','Talking about one female fictional classmate uses ella.',['ella','tú','usted']),
 q('target-ser','ser','¿De dónde ___ tú?',['eres'],'¿De dónde eres tú?','Tú takes eres.'),
 q('target-perspective','perspective','Ana habla por Ana y Sofía: ___ amigas.',['Somos','Nosotras somos'],'Nosotras somos amigas.','The speaker includes herself in an all-female group.'),
 q('target-objects','objects','¿Qué objeto muestra la hora?',['el reloj'],'el reloj','The clock shows the time.',['el reloj','la regla','el mapa']),
 q('target-hay','hay','En esta escena imaginada, ___ tres libros en la mesa.',['hay'],'Hay tres libros en la mesa.','Hay does not change in the plural.'),
 q('target-articles','articles','Escribe el plural de una clase.',['unas clases'],'unas clases','Feminine plural: unas clases.'),
 q('target-likes','likes','No me ___ las ciencias.',['gustan'],'No me gustan las ciencias.','Ciencias is plural, so use gustan.'),
 q('target-adjectives','adjectives','La clase es ___. (fun)',['divertida'],'La clase es divertida.','Feminine singular: divertida.'),
 q('target-uses','uses','El concierto es el viernes. ¿Qué describe SER?',['Tiempo del evento'],'Tiempo del evento','SER gives the event’s time.',['Tiempo del evento','Origen','Posesión'])
];
export const stations = [
 {id:'teacher',name:'Sra. Abarca',title:'¡Hola, profesora!',note:'Preséntate · introduce yourself',color:'#f37053',position:[-3,0,-3],questionIds:['self-intro','usted','ella']},
 {id:'mateo',name:'Mateo',title:'Un nuevo compañero',note:'Tú y yo · have a conversation',color:'#2faaa1',position:[3,0,1],questionIds:['mateo-response','tu','self-pronoun']},
 {id:'supplies',name:'Los útiles',title:'Explora los objetos',note:'Descubre · inspect classroom supplies',color:'#e4a829',position:[-3,0,2],questionIds:['erase','measure','cut']},
 {id:'backpack',name:'La mochila',title:'¿Qué hay?',note:'Prepara · pack and inspect',color:'#7089d8',position:[0,0,2],questionIds:['inventory-cuaderno','inventory-tijeras','plural-hay']},
 {id:'schedule',name:'El horario',title:'Mis clases',note:'Elige · subjects and likes',color:'#2a9b85',position:[4,0,-3],questionIds:['schedule','music','math','dislike','fun']},
 {id:'group',name:'Los compañeros',title:'¿Quién habla?',note:'Cambia · change perspective',color:'#d15f8d',position:[1,0,-1],questionIds:['fernando','victoria','ellas','ellos','nosotras','students']},
 {id:'doctor',name:'La pizarra',title:'Detective de SER',note:'Conecta · discover DOCTOR',color:'#5979ac',position:[0,0,-4],questionIds:['occupation','relationship','origin','time']},
 {id:'band',name:'La sala de música',title:'¡Somos músicos!',note:'Celebra · unlock after 4 missions',color:'#de953c',position:[-4,0,-1],questionIds:['band-self','band-group']}
];
export const questionById = (id:string) => [...questions,...reviewQuestions].find(q=>q.id===id)!;
export const initialInventory:Record<string,number>={cuaderno:1,lapiz:2,libro:0,tijeras:0,borrador:0,boligrafo:0,regla:0,carpeta:0};
export const packItems = [
 {id:'cuaderno',singular:'un cuaderno',plural:'cuadernos',name:'el cuaderno'}, {id:'lapiz',singular:'un lápiz',plural:'lápices',name:'el lápiz'}, {id:'libro',singular:'un libro',plural:'libros',name:'el libro'}, {id:'tijeras',singular:'unas tijeras',plural:'tijeras',name:'las tijeras'}, {id:'borrador',singular:'un borrador',plural:'borradores',name:'el borrador'}, {id:'boligrafo',singular:'un bolígrafo',plural:'bolígrafos',name:'el bolígrafo'}, {id:'regla',singular:'una regla',plural:'reglas',name:'la regla'}, {id:'carpeta',singular:'una carpeta',plural:'carpetas',name:'la carpeta · extra'}
];
export function inventoryQuestion(id:string,inventory:Record<string,number>):Question {
 const item=packItems.find(i=>i.id===id)!; const count=inventory[id]??0; const answer=count?'Sí, hay':'No, no hay';
 return q('inventory-'+id,'hay',`¿Hay ${item.singular} en la mochila?`,[answer],count?`Sí, hay ${count===1?item.singular:count+' '+item.plural}.`:`No, no hay ${item.plural}.`,'Answer from the backpack you can see. Hay is unchanged with singular or plural quantities.',['Sí, hay','No, no hay'],{visual:'backpack',source:'Generated from current visible inventory · new practice'});
}
export function inventoryPluralQuestion(inventory:Record<string,number>):Question {const count=inventory.lapiz??0;const noun=count===1?'un lápiz':count?count+' lápices':'lápices';return q('inventory-plural','hay',`En esta mochila, ___ ${noun}.`,[count?'hay':'no hay'],`${count?'Hay':'No hay'} ${noun} en esta mochila.`,'Use the visible pencil count. Hay is unchanged for one or several items.',undefined,{visual:'backpack',source:'Current visible inventory · new practice',help:'Describe the pencils currently in this backpack.'});}
