import type {CSSProperties} from 'react';
import {choiceGloss,choiceObject,examples} from './intuitive';
import './learning-visuals.css';
import type {StoryTurn,StoryConcept} from './story-content';
const portraitCenters:Record<string,[number,number]>={'Sra. Abarca':[169,34],Mateo:[62,79],Sofía:[132,84],Carlos:[214,80],Ana:[270,86]};
export function Portrait({name,size='normal'}:{name:string;size?:'normal'|'large'}) {const center=portraitCenters[name];return <span className={`learn-portrait ${size==='large'?'large':''} ${center?'illustrated':'learner'}`} style={center?{'--face-x':center[0]+'px','--face-y':center[1]+'px'} as CSSProperties:undefined} aria-hidden="true">{!center&&(name==='Yusuf'?'Y':name.slice(0,1))}</span>}
const cells:Record<string,[number,number]>={lapiz:[0,0],borrador:[1,0],cuaderno:[2,0],tijeras:[0,1],regla:[1,1],libro:[2,1],calculadora:[0,2],estuche:[1,2],goma:[2,2]};
export function SupplyArt({id}:{id:string}) {const cell=cells[id];return cell?<span className="learn-supply" style={{backgroundPosition:`${cell[0]*50}% ${cell[1]*50}%`}} aria-hidden="true"/>:<span className="learn-symbol" aria-hidden="true">{({reloj:'◷',carpeta:'📂',puerta:'🚪',ventana:'▥',papelera:'♲',silla:'🪑',mapa:'🗺️',musica:'♫',ciencias:'⚗',matematicas:'＋',arte:'🎨'} as Record<string,string>)[id]??'✦'}</span>}
export function ChoiceVisual({value,english}:{value:string;english:boolean}) {const object=choiceObject(value);const person=['Mateo','Sofía','Carlos','Ana'].find(p=>value===p||value===`Ella es ${p}.`||value===`Él es ${p}.`);const gloss=choiceGloss(value);return <>{object&&<SupplyArt id={object}/>} {!object&&person&&<Portrait name={person}/>}<span className="learn-option-copy"><b lang="es">{value}</b>{english&&gloss&&<small lang="en">{gloss}</small>}</span></>}
export function TeachingExample({concept,turn,english,tryIt,listen,canListen}:{concept:StoryConcept;turn:StoryTurn;english:boolean;tryIt:()=>void;listen:(line:string)=>void;canListen:boolean}) {const example=concept==='uses'&&turn.serUse!=='Posesión'?{...examples.uses,phrase:turn.model,meaning:turn.help,pattern:[turn.serUse??'SER','es / son',turn.model] as [string,string,string]}:examples[concept];const spanishPatterns:Record<string,string>={'Me':'Yo','You':'Tú','Teacher · you':'Profesora · usted','Mateo + me':'Mateo + yo','You + you':'Tú + tú','One or more':'Uno o más','same word':'misma palabra','Write':'Escribir','My class':'Mi clase','One / more':'Uno / varios','the thing liked':'lo que me gusta','Whose book?':'¿De quién es?'};return <section className="learn-example" aria-label={english?'See an example':'Mira un ejemplo'}><span className="learn-example-label">{english?'Watch first':'Primero, mira'}</span><h2 lang={english?'en':'es'}>{english?example.title:example.titleEs}</h2><div className="learn-example-person">{example.object?<SupplyArt id={example.object}/>:<Portrait name={example.person.split(' + ')[0]} size="large"/>}<div><b>{example.person}</b><p lang="es">{example.phrase}</p>{english&&<small lang="en">{example.meaning}</small>}</div></div><div className="learn-pattern" lang={english?'en':'es'} aria-label="Person to pronoun to expression">{example.pattern.map((part,i)=><span key={part}><b>{english?part:spanishPatterns[part]??part}</b>{i<2&&<i aria-hidden="true">→</i>}</span>)}</div><div className="learn-example-actions"><button onClick={()=>listen(example.phrase)} disabled={!canListen} aria-label="Listen to the example">♫ {english?'Listen':'Escuchar'}</button><button className="day-primary" onClick={tryIt}>{english?'Now I try':'Ahora yo'} →</button></div><small>{english?'You can see this example again anytime.':'Puedes volver a ver el ejemplo cuando quieras.'}</small></section>}
