"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Classroom from './Classroom';
import {adjectives,doctor,extraQuestions,inventoryPluralQuestion,inventoryQuestion,packItems,pronouns,questionById,questions,reviewQuestions,targetedQuestions,skillLabels,stations,subjects,vocabulary,type Question,type Skill} from './content';
import {completeMission,discover,emptyProgress,grade,loadProgress,missedSkills,practiceGrade,recordAnswer,saveProgress,shuffle,STORAGE_KEY,type Progress} from './learning';
import './spanish.css';
import './grades.css';
const ROOT='/quizzes/spanish/';const ADVENTURE=ROOT+'unit-2/';
type Update=(fn:(p:Progress)=>Progress)=>void;
function Backpack({progress,update,editable=true}:{progress:Progress;update:Update;editable?:boolean}){
 return <section className="backpack"><h3>¿Qué hay en la mochila?</h3><div className="inventory" data-testid="inventory">{packItems.map(i=><div className={`inventory-item ${progress.inventory[i.id]?'packed':''}`} key={i.id}><span>{i.name}</span><div>{editable&&<button aria-label={`Remove ${i.name}`} disabled={!progress.inventory[i.id]} onClick={()=>update(p=>({...p,inventory:{...p.inventory,[i.id]:Math.max(0,p.inventory[i.id]-1)}}))}>−</button>}<strong aria-label={`${progress.inventory[i.id]} ${i.plural}`}>{progress.inventory[i.id]}</strong>{editable&&<button aria-label={`Add ${i.name}`} disabled={progress.inventory[i.id]>=5} onClick={()=>update(p=>({...p,inventory:{...p.inventory,[i.id]:Math.min(5,p.inventory[i.id]+1)}}))}>+</button>}</div></div>)}</div><p className="spanish-model">{packItems.filter(i=>progress.inventory[i.id]>0).map(i=>`Hay ${progress.inventory[i.id]===1?i.singular:progress.inventory[i.id]+' '+i.plural}.`).join(' ')||'No hay útiles en la mochila.'}</p></section>;
}
function Perspective({q}:{q:Question}){if(!q.speaker&&!q.about&&!q.listeners)return null;return <div className="perspective" aria-label="Conversation perspective">{q.speaker&&<div><small>Habla · speaker</small><span className="speaker-person">{q.speaker}</span></div>}{q.listeners?.length&&<div><small>Escucha · addressed</small>{q.listeners.map(p=><span className="listener-person" key={p}>{p}</span>)}</div>}{q.about?.length&&<div><small>Sobre · talking about</small>{q.about.map(p=><span className={p===q.speaker?'speaker-person':'about-person'} key={p}>{p}{p===q.speaker?' · yo':''}</span>)}</div>}</div>}
function QuestionCard({q,english,onResult,onNext,nextLabel='Continuar',speak,canSpeak,check=false}:{q:Question;english:boolean;onResult:(correct:boolean,first:boolean,hinted:boolean)=>void;onNext:()=>void;nextLabel?:string;speak:(text:string)=>void;canSpeak:boolean;check?:boolean}){
 const [answer,setAnswer]=useState('');const [feedback,setFeedback]=useState<ReturnType<typeof grade>|null>(null);const [hint,setHint]=useState(false);const first=useRef(true);const submitted=useRef(false);const input=useRef<HTMLInputElement>(null);const questionHeading=useRef<HTMLHeadingElement>(null);useEffect(()=>{questionHeading.current?.focus()},[]);const hinted=useRef(false);const [choices]=useState(()=>shuffle(q.options??[]));
 const submit=(value=answer)=>{if(submitted.current||!value.trim())return;submitted.current=true;setAnswer(value);const result=grade(q,value);setFeedback(result);onResult(result.correct,first.current,hinted.current);first.current=false;};
 return <section className="question-card" aria-label="Practice question"><Perspective q={q}/><div className="question-heading"><span className="skill-tag">{skillLabels[q.skill]}</span><button className="audio-button" disabled={!canSpeak} onClick={()=>speak(q.prompt)} aria-label="Listen to Spanish question">Escuchar</button></div><h3 ref={questionHeading} tabIndex={-1} lang="es">{q.prompt}</h3>{english&&<p className="english-help">{q.help}</p>}{q.visual==='pencil'&&<div className="pencil-note" aria-label="Pencil mistake: dos más dos equals cinco"><span>Nota de lápiz</span><s>2 + 2 = 5</s><strong>Hay un error de lápiz.</strong></div>}{q.options?<div className="answer-options">{choices.map(o=><button key={o.id} disabled={!!feedback} className={answer===o.id?'selected':''} onClick={()=>submit(o.id)}>{o.text}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();submit()}}><label htmlFor="spanish-answer">Tu respuesta</label><input ref={input} id="spanish-answer" autoComplete="off" value={answer} disabled={!!feedback} onChange={e=>setAnswer(e.target.value)} placeholder="Escribe en español…"/><div className="accent-keys" aria-label="Spanish accent keyboard">{['á','é','í','ó','ú','ñ','ü','¿','¡'].map(c=><button type="button" key={c} disabled={!!feedback} onClick={()=>{const el=input.current;const start=el?.selectionStart??answer.length,end=el?.selectionEnd??answer.length;setAnswer(answer.slice(0,start)+c+answer.slice(end));requestAnimationFrame(()=>{el?.focus();el?.setSelectionRange(start+1,start+1)})}}>{c}</button>)}</div><button className="primary" disabled={!!feedback||!answer.trim()}>Comprobar</button></form>}
 {!feedback&&<button className="text-button" onClick={()=>{setHint(true);hinted.current=true}}>Una pista</button>}{hint&&<p className="hint" lang="es">Pista: {q.hint}</p>}{feedback&&<div className={`feedback ${feedback.correct?'correct':'retry'}`} role="status"><strong>{feedback.correct?'¡Bien hecho!':'Casi. Vamos a practicar.'}</strong><p lang="es">{q.model}</p>{english&&<><p>{q.explanation}</p>{feedback.spelling&&<p>{feedback.spelling}</p>}{!feedback.correct&&<p>{feedback.diagnostic} Your answer: <span>{answer}</span></p>}</>}{!feedback.correct&&<button onClick={()=>{submitted.current=false;setFeedback(null);setAnswer('');requestAnimationFrame(()=>input.current?.focus())}}>Intentar otra vez</button>}{(feedback.correct||check)&&<button className="primary" onClick={onNext}>{nextLabel}</button>}</div>}<small className="source-note">{q.source}</small></section>;
}
function Guide({progress}:{progress:Progress}){
 const [tab,setTab]=useState('words');const [search,setSearch]=useState('');
 return <section className="guide"><div className="section-title"><div><p className="eyebrow">Tu cuaderno de campo</p><h2>Guía de exploración</h2></div><span>{progress.discoveries.length} descubrimientos</span></div><div className="guide-tabs" aria-label="Field guide sections">{[['words','Vocabulario'],['people','Pronombres + SER'],['patterns','Clases + gramática'],['doctor','DOCTOR']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='words'&&<><label htmlFor="word-search">Buscar una palabra</label><input id="word-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="mochila, eraser…"/><div className="word-grid">{vocabulary.filter(v=>v.join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(([id,es,en,line])=><article key={id}><span className="collected">{progress.discoveries.includes(id)?'✓ Descubierto':'Por descubrir'}</span><h3 lang="es">{es}</h3>{progress.english&&<p>{en}</p>}<p lang="es">{line}</p></article>)}</div><p>La goma means glue on this class list; dialects can also use it for eraser. La carpeta is exercise enrichment.</p></>}
 {tab==='people'&&<><div className="table-scroll"><table><caption>Todos los pronombres y formas de SER</caption><thead><tr><th>Pronombre</th><th>Significado</th><th>SER</th></tr></thead><tbody>{pronouns.map(([p,en,ser])=><tr key={p}><th lang="es">{p}</th><td>{en}</td><td lang="es"><strong>{ser}</strong></td></tr>)}</tbody></table></div><div className="guide-callout"><h3>¿Quién habla? ¿A quién?</h3><p>Yusuf: <strong>Yo soy</strong> estudiante. Mateo asks: ¿<strong>Tú eres</strong> estudiante? Yusuf answers: Sí, <strong>soy</strong> estudiante.</p><p>Talking ABOUT Ana y Sofía: <strong>ellas son</strong>. Talking TO them: <strong>ustedes son</strong>. Sofía including herself: <strong>nosotras somos</strong>.</p><p>Fernando y yo: <strong>nosotros somos</strong>. A mixed group spoken about: <strong>ellos son</strong>. Vosotros / vosotras → <strong>sois</strong>, mainly in Spain.</p><p><strong>Él</strong> = he; <strong>el</strong> = the. <strong>Tú</strong> = you; <strong>tu</strong> = your.</p></div></>}
 {tab==='patterns'&&<><div className="word-grid"><article><h3>Artículos</h3><p>el / un libro · la / una mochila</p><p>los / unos libros · las / unas mochilas</p><p>un lápiz → unos lápices</p><p>la mochila → las mochilas · <strong>el mapa</strong></p></article><article><h3>Hay</h3><p>Hay un cuaderno. Hay dos lápices.</p><p>¿Hay tijeras? Sí, hay. / No, no hay.</p><p>Hay quince mochilas = fifteen backpacks.</p><p>La mesa = table. El escritorio = desk.</p></article><article><h3>Gustos</h3><p>Me gusta la música. Me gustan las matemáticas.</p><p>A mí me gusta(n)… A ti te gusta(n)… A él / ella le gusta(n)…</p><p>No me gusta la música. No me gustan las matemáticas.</p><p>Agreement follows the thing liked.</p></article><article><h3>Adjetivos</h3><p>Una estudiante organizada. Dos estudiantes organizadas.</p><p>Las clases son divertidas. Los compañeros son simpáticos.</p><p>Fácil → fáciles · difícil → difíciles.</p></article></div><h3>Las asignaturas</h3><div className="chips">{subjects.map(s=><span key={s} lang="es">{s}</span>)}</div><h3>Describe a los compañeros</h3><ul className="adjective-list">{adjectives.map(a=><li key={a}>{a}</li>)}</ul><h3>Preguntas para conversar</h3><p>¿Qué usas en la clase? ¿Qué clases tienes? ¿Qué clases te gustan? ¿De dónde eres? ¿Quién es tu profesor(a)? ¿Cómo es tu profesor(a)? ¿Cómo son tus clases? ¿Cómo son tus compañeros? ¿Cómo eres?</p><p>Use fictional origin details or skip personal disclosure. A pen can help you study; we do not score “Para estudiar necesito un bolígrafo” as universally false.</p></>}
 {tab==='doctor'&&<><div className="doctor-grid">{doctor.map(([letter,name,example,explanation])=><article key={name}><span>{letter}</span><div><h3>{name}</h3><p lang="es">{example}</p>{progress.english&&<p>{explanation}</p>}</div></article>)}</div><p className="guide-callout">Descripción and características overlap. Both can describe qualities; there is no single-answer trap between them. DOCTOR is a memory aid, not a universal permanent/temporary rule.</p></>}
 <details className="content-notes"><summary>Fuentes y notas · sources and learning goals</summary><p>Vocabulary and SER are based on the supplied Unit 2 class list (filename 2024–2025) and pronoun/SER chart. DOCTOR is based on the supplied SER uses chart. Dialogues, fictional schedule, quizzes, and missions are new practice examples. Sra. Abarca’s dialogue and all classmates are fictional practice characters.</p><p>We use interpretive reading, simulated conversation, and short presentational responses. These are design mappings. <a href="https://www.fultonschools.org/all-departments/academics/learning-teaching/curriculum/world-languages/program-goals" target="_blank" rel="noreferrer">Fulton County’s Program Goals</a> describes Level 1 novice communication on familiar topics and a classroom target-language expectation. This game is not district endorsed or a certified proficiency assessment; detailed standard codes have not been verified.</p></details>
 </section>;
}
function SkillSummary({progress}:{progress:Progress}){return <div className="skills-grid">{(Object.entries(skillLabels) as [Skill,string][]).map(([id,label])=>{const s=progress.skills[id];return <article key={id}><strong>{label}</strong><span>{s?`${s.independentCorrect} / ${s.firstTotal}`:'Por explorar'}</span><small>{s?`First responses: ${s.firstCorrect} correct · ${s.hints} supported · ${s.corrections} corrections`:'Independent first responses'}</small></article>})}</div>}
function Schedule(){return <section className="schedule"><h3>Mi horario · martes ficticio</h3><p>A fictional schedule. Explore all Unit 2 subjects; these are not Yusuf’s real classes or times.</p><div className="schedule-grid">{subjects.map((s,i)=><div key={s}><time>{`${8+Math.floor(i/2)}:${i%2?'30':'00'}`}</time><span lang="es">{s}</span></div>)}</div><p className="spanish-model">Tengo la clase de música. Me gusta la música. No me gustan las clases difíciles.</p></section>}
function StationDialog({stationId,item,progress,update,close,speak,canSpeak}:{stationId:string;item?:string;progress:Progress;update:Update;close:()=>void;speak:(s:string)=>void;canSpeak:boolean}){
 const station=stations.find(s=>s.id===stationId)!;const [index,setIndex]=useState(0);const [finished,setFinished]=useState(false);const [selected,setSelected]=useState(item??'');const dialog=useRef<HTMLDialogElement>(null);const restoreFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{restoreFocus.current=document.activeElement as HTMLElement;dialog.current?.showModal();return()=>{restoreFocus.current?.focus()}},[]);
 const qid=station.questionIds[index];const q=qid==='plural-hay'?inventoryPluralQuestion(progress.inventory):qid?.startsWith('inventory-')?inventoryQuestion(qid.replace('inventory-',''),progress.inventory):questionById(qid);const chosen=vocabulary.find(v=>v[0]===selected);
 const complete=()=>{if(index+1<station.questionIds.length)setIndex(i=>i+1);else {update(p=>completeMission(p,station.id));setFinished(true);}};
 // Backdrop clicking supplements native Escape and the visible Close button.
 // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions
 return <dialog ref={dialog} className="station-dialog" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===dialog.current)close()}} aria-labelledby="station-title"><div className="dialog-top"><span className="station-number">{stations.indexOf(station)+1}</span><div><p className="eyebrow">{station.name}</p><h2 id="station-title">{station.title}</h2></div><button className="close-dialog" onClick={close} aria-label="Close conversation">×</button></div><div className="dialog-content">
 {stationId==='teacher'&&<p className="scene-context" lang="es">Bienvenido, Yusuf. Soy la profesora Abarca. Vamos a conocer la clase.</p>}
 {stationId==='mateo'&&<p className="scene-context" lang="es">¡Hola! Soy Mateo. Soy estudiante. Me gusta la música. ¿Y tú?</p>}
 {stationId==='supplies'&&<section><h3>Busca, toca y descubre</h3><p>{progress.english?'Inspect any object. Each discovery adds 5 XP once. Then try a classroom task.':'Toca un objeto. Cada descubrimiento cuenta una vez.'}</p><div className="object-shelf">{vocabulary.map(([id,es])=><button key={id} onClick={()=>{setSelected(id);update(p=>discover(p,id))}} aria-pressed={selected===id}>{progress.discoveries.includes(id)?'✓ ':''}{es}</button>)}</div>{chosen&&<div className="object-detail"><h3 lang="es">{chosen[1]}</h3>{progress.english&&<p>{chosen[2]}</p>}<p lang="es">{chosen[3]}</p><button disabled={!canSpeak} onClick={()=>speak(chosen[1]+'. '+chosen[3])}>Escuchar</button></div>}</section>}
 {stationId==='backpack'&&<Backpack progress={progress} update={update}/>}{stationId==='schedule'&&<Schedule/>}{stationId==='doctor'&&<div className="mini-doctor">{doctor.map(([letter,name,ex])=><div key={name}><b>{letter} · {name}</b><span lang="es">{ex}</span></div>)}</div>}
 {stationId==='group'&&<p className="scene-context">Follow the highlighted speaker, listeners, and people being discussed. Yusuf and Fernando, Ana and Sofía, and Victoria all join the conversation.</p>}
 {stationId==='band'&&<div className="band-welcome"><strong>★ ¡La sala de música está abierta!</strong><p lang="es">Soy músico. Somos músicos. ¡Bienvenidos a la banda!</p><p>Músico, banda and directora are music enrichment. Imagine playing your favorite rhythm; no sound or microphone is needed.</p></div>}
 {!finished&&<><div className="mission-step">Misión · {index+1} / {station.questionIds.length}</div><QuestionCard key={qid+(stationId==='backpack'?JSON.stringify(progress.inventory):'')} q={q} english={progress.english} speak={speak} canSpeak={canSpeak} onResult={(correct,first,hinted)=>update(p=>recordAnswer(p,q.skill,correct,first,hinted))} onNext={complete} nextLabel={index+1===station.questionIds.length?'Completar misión':'Continuar'}/></>}
 {finished&&<div className="mission-complete" role="status"><span>✓</span><h3>¡Misión cumplida!</h3><p>You can return anytime. Your discoveries and progress are saved on this browser.</p><p>{progress.missions.filter(x=>x!=='band').length>=4?'La sala de música está abierta.':`${Math.max(0,4-progress.missions.filter(x=>x!=='band').length)} more missions to the band room.`}</p><button className="primary" onClick={close}>Volver a explorar</button></div>}
 </div></dialog>;
}
function Quiz({progress,update,speak,canSpeak}:{progress:Progress;update:Update;speak:(s:string)=>void;canSpeak:boolean}){
 const [session,setSession]=useState<Question[]|null>(null);const [index,setIndex]=useState(0);const [kind,setKind]=useState('short');const [check,setCheck]=useState(false);const [firstResults,setFirstResults]=useState<{correct:boolean;hinted:boolean}[]>([]);const [finished,setFinished]=useState(false);const nextGuard=useRef(false);
 const fullCount=questions.length+reviewQuestions.length+extraQuestions.length+packItems.length;
 function start(mode:string){const missed=missedSkills(progress);const pool=mode==='review'?targetedQuestions.filter(q=>missed.includes(q.skill)):[...questions,...reviewQuestions,...extraQuestions,...packItems.map(i=>inventoryQuestion(i.id,progress.inventory))];let list=shuffle(pool);if(mode==='short'){const core=['self-intro','erase','music','fernando','pencils','tu'];list=shuffle([...core.map(questionById),inventoryQuestion('tijeras',progress.inventory),questionById('occupation')]);}if(mode==='full')setCheck(true);setSession(list);setIndex(0);setKind(mode);setFirstResults([]);setFinished(false);nextGuard.current=false;}
 if(!session)return <section className="quiz-menu"><p className="eyebrow">Una pregunta a la vez</p><h2>Comprueba lo que sabes</h2><p>Explore whenever you like. The big quiz gives a private practice grade from independent first answers; corrections and hints stay separate.</p><label className="check-switch"><input type="checkbox" checked={check} onChange={e=>setCheck(e.target.checked)}/>Grade my short session · record first answers, then review</label><div className="quiz-options"><button onClick={()=>start('short')}><span>08</span><strong>Una vuelta corta</strong><small>8 mixed questions · a few minutes</small></button><button onClick={()=>start('full')}><span>{fullCount}</span><strong>El gran quiz · con nota</strong><small>{fullCount} questions · percentage + letter grade</small></button><button onClick={()=>start('review')} disabled={!missedSkills(progress).length}><span>↻</span><strong>Repasar mis habilidades</strong><small>{missedSkills(progress).length?missedSkills(progress).map(s=>skillLabels[s]).join(' · '):'Review appears after a missed or supported first response'}</small></button></div><GradeHistory progress={progress}/><h3>Tu evidencia de aprendizaje</h3><SkillSummary progress={progress}/></section>;
 if(finished){const result=practiceGrade(firstResults.filter(r=>r.correct&&!r.hinted).length,session.length);return <section className="quiz-finish"><span className="finish-star">★</span><h2>¡Buen trabajo!</h2>{check&&<div className="grade-result" aria-label="Practice grade"><strong>{result.percent}%</strong><span>{result.letter}</span><p>Private practice grade · A 90+, B 80+, C 70+, D 60+. Below 60: more practice.</p></div>}<p>{result.correct} / {session.length} independent correct first responses</p><p>{firstResults.filter(r=>r.correct&&r.hinted).length} correct with a hint. Corrections are practice, and stay separate from first responses. This is a practice grade, not a school-issued grade or proof of proficiency.</p><h3>¿Qué puedes practicar ahora?</h3><SkillSummary progress={progress}/><div className="row-actions"><button className="primary" onClick={()=>start(kind)}>Otra vuelta</button><button onClick={()=>setSession(null)}>Elegir otro modo</button><a className="button" href={ADVENTURE}>Volver a la clase</a></div></section>;}
 const q=session[index];return <section className="quiz-session"><div className="quiz-progress"><span>Pregunta {index+1} de {session.length}</span><button onClick={()=>setSession(null)}>Salir del quiz</button></div><progress value={index} max={session.length} aria-label="Quiz progress"/>{q.visual==='backpack'&&<Backpack progress={progress} update={update} editable={false}/>}<QuestionCard key={q.id+'-'+index} q={q} english={progress.english} check={check} speak={speak} canSpeak={canSpeak} onResult={(correct,first,hinted)=>{update(p=>recordAnswer(p,q.skill,correct,first,hinted));if(first)setFirstResults(r=>[...r,{correct,hinted}]);}} onNext={()=>{if(nextGuard.current)return;nextGuard.current=true;if(index+1===session.length){if(check){const result=practiceGrade(firstResults.filter(r=>r.correct&&!r.hinted).length,session.length);update(p=>({...p,grades:[...p.grades,result].slice(-10)}));}setFinished(true);}else {setIndex(i=>i+1);requestAnimationFrame(()=>{nextGuard.current=false})}}} nextLabel={index+1===session.length?'Ver mi progreso':'Siguiente pregunta'}/></section>;
}
function GradeHistory({progress}:{progress:Progress}){if(!progress.grades.length)return null;return <section className="grade-history"><h3>Mis notas de práctica</h3><p>Saved only in this browser.</p>{[...progress.grades].reverse().map((g,i)=><div key={g.date+'-'+i}><time>{new Date(g.date).toLocaleDateString()}</time><strong>{g.percent}% · {g.letter}</strong><span>{g.correct} / {g.total} first answers</span></div>)}</section>}
export default function SpanishApp({view}:{view:'hub'|'adventure'|'quiz'|'guide'}){
 const [progress,setProgress]=useState<Progress>(emptyProgress);const [ready,setReady]=useState(false);const [warning,setWarning]=useState('');const [room,setRoom]=useState<'classroom'|'band'>('classroom');const [selection,setSelection]=useState<{id:string;item?:string}|null>(null);const [notice,setNotice]=useState('');const [reset,setReset]=useState(false);const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);const [voice,setVoice]=useState('');const resetRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{try{const saved=loadProgress(window.localStorage);setProgress(saved.progress);setWarning(saved.warning)}catch{setWarning('Browser storage is blocked. You can still play during this visit.')}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{const message=saveProgress(window.localStorage,progress);if(message)setWarning(message)}catch{setWarning('Saving is blocked. Your progress lasts for this visit.')}},[progress,ready]);
 useEffect(()=>{if(!('speechSynthesis' in window))return;const load=()=>{const available=window.speechSynthesis.getVoices().filter(v=>/^es([_-]|$)/i.test(v.lang));setVoices(available);setVoice(v=>v||available[0]?.voiceURI||'')};load();window.speechSynthesis.addEventListener('voiceschanged',load);return()=>{window.speechSynthesis.removeEventListener('voiceschanged',load);window.speechSynthesis.cancel()}},[]);
 useEffect(()=>{if(reset)resetRef.current?.showModal()},[reset]);
 const update:Update=useCallback(fn=>setProgress(p=>fn(p)),[]);const fallback=useCallback(()=>{setProgress(p=>({...p,mode:'2d'}));setNotice('3D is unavailable here. Every mission and learning tool is available in the 2D station list.')},[]);
 const unlocked=progress.missions.filter(id=>id!=='band').length>=4;
 const select=useCallback((id:string,item?:string)=>{if(id==='band'&&!unlocked){setNotice('Complete any 4 classroom missions to open the band room. The guide and quiz are always available.');return;}if(id==='band')setRoom('band');if(item)setProgress(p=>discover(p,item));setSelection({id,item})},[unlocked]);
 const speak=(text:string)=>{const selected=voices.find(v=>v.voiceURI===voice);if(progress.quiet||!selected||!('speechSynthesis' in window)){setNotice('Text is always available. Enable audio and choose an available Spanish voice to listen.');return;}window.speechSynthesis.cancel();const line=new SpeechSynthesisUtterance(text);line.voice=selected;line.lang=selected.lang;line.rate=.85;line.onerror=()=>setNotice('Audio could not play. Read the same Spanish text on screen.');window.speechSynthesis.speak(line);};useEffect(()=>{if(progress.quiet&&'speechSynthesis' in window)window.speechSynthesis.cancel()},[progress.quiet]);const canSpeak=!progress.quiet&&!!voices.find(v=>v.voiceURI===voice);
 return <div className="spanish-app" data-ready={ready} aria-busy={!ready}><a className="skip-link" href="#spanish-main">Skip to study activity</a><header className="spanish-topbar"><a className="spanish-brand" href="/"><span>Y7</span>Yusuf’s study club</a><nav aria-label="Spanish study navigation"><a href={ROOT} aria-current={view==='hub'?'page':undefined}>Español</a><a href={ADVENTURE} aria-current={view==='adventure'?'page':undefined}>Explorar</a><a href={ADVENTURE+'guide/'} aria-current={view==='guide'?'page':undefined}>Guía</a><a href={ADVENTURE+'quiz/'} aria-current={view==='quiz'?'page':undefined}>Quiz</a></nav><span className="xp-badge">★ {progress.xp} XP</span></header>
 <main id="spanish-main"><div className="spanish-heading"><div><p className="eyebrow">Español · Unidad 2</p><h1>{view==='quiz'?'¡A practicar!':view==='guide'?'Tu guía de campo':'Mis clases y mis compañeros'}</h1></div><div className="settings"><button aria-pressed={progress.english} onClick={()=>update(p=>({...p,english:!p.english}))}>English help {progress.english?'on':'off'}</button><button aria-pressed={!progress.quiet} onClick={()=>update(p=>({...p,quiet:!p.quiet}))}>{progress.quiet?'Audio off':'Audio on'}</button>{!progress.quiet&&voices.length>0&&<select aria-label="Spanish voice" value={voice} onChange={e=>setVoice(e.target.value)}>{voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name}</option>)}</select>}</div></div>{!progress.quiet&&<p className="audio-note">{voices.length?'Audio plays only when you press Escuchar. Voice quality and offline availability vary.':'No Spanish voice is available in this browser. All Spanish is shown as text.'}</p>}{warning&&<p className="save-warning" role="status">{warning}</p>}{notice&&<p className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notice">×</button></p>}
 {view==='hub'&&<><section className="adventure-ticket"><div className="ticket-copy"><span className="ticket-label">TU PRÓXIMA AVENTURA</span><h2>¡Bienvenido a la clase, Yusuf!</h2><p lang="es">Conoce a tus compañeros. Descubre los útiles. Prepara tu mochila. ¡La banda te espera!</p>{progress.english&&<p>Meet the class, explore the room, and follow small missions to the band room.</p>}<div className="row-actions"><a className="button primary" href={ADVENTURE}>{progress.missions.length?'Continuar mi aventura':'Entrar en la clase'}</a><a className="button" href={ADVENTURE+'quiz/'}>Ir al quiz</a></div></div><div className="ticket-progress"><span className="big-number">{progress.missions.length}<small>/ 8</small></span><strong>misiones completadas</strong><div className="mission-stamps">{stations.map((s,i)=><span key={s.id} title={s.name} className={progress.missions.includes(s.id)?'stamped':''}>{progress.missions.includes(s.id)?'✓':i+1}</span>)}</div><p>{unlocked?'♪ La sala de música está abierta.':'Complete any 4 missions to open the band room.'}</p></div></section><div className="hub-grid"><section className="hub-tools"><p className="eyebrow">Siempre a tu alcance</p><h2>Elige tu camino</h2><a href={ADVENTURE+'guide/'}><strong>Guía de campo</strong><span>Vocabulary, every SER form, and classroom patterns</span></a><a href={ADVENTURE+'quiz/'}><strong>Práctica a tu ritmo</strong><span>Short quiz, full practice, or review missed skills</span></a><a href="/quizzes/ecology/"><strong>Ecology Expedition</strong><span>Return to your science adventure</span></a></section><section className="mission-board"><p className="eyebrow">Misiones de la clase</p><h2>¿Dónde quieres empezar?</h2>{stations.slice(0,4).map(s=><a key={s.id} href={ADVENTURE+'?station='+s.id}><span>{progress.missions.includes(s.id)?'✓':'○'}</span><div><strong>{s.name}</strong><small>{s.note}</small></div></a>)}</section></div></>}
 {view==='adventure'&&<div className="explore-layout"><section className="play-space"><div className="scene-toolbar">{room==='band'&&<button onClick={()=>setRoom('classroom')}>Volver a la clase</button>}<span>{room==='band'?'La sala de música':'La clase de español'}</span><div><button aria-pressed={progress.mode==='3d'} onClick={()=>update(p=>({...p,mode:'3d'}))}>3D</button><button aria-pressed={progress.mode==='2d'} onClick={()=>update(p=>({...p,mode:'2d'}))}>2D / lista</button></div></div>{progress.mode==='3d'?(ready?<Classroom onSelect={select} onFallback={fallback} unlocked={unlocked} band={room==='band'}/>:<div className="room-loading" role="status">Preparando la clase…</div>):<div className="map-list"><p className="eyebrow">Explora sin mover la cámara</p><h2>Tu clase, estación por estación</h2><p>Every object, conversation, and mission is available here.</p><div>{stations.map((s,i)=><button key={s.id} onClick={()=>select(s.id)} style={{borderColor:s.color}}><span>{progress.missions.includes(s.id)?'✓':i+1}</span><strong>{s.name}</strong><small>{s.note}</small></button>)}</div></div>}<div className="explore-status"><span>✓ {progress.discoveries.length} descubrimientos</span><span>♪ {unlocked?'Música abierta':`${Math.max(0,4-progress.missions.filter(id=>id!=='band').length)} misiones para música`}</span><a href={ADVENTURE+'guide/'}>Abrir la guía</a></div></section><aside className="station-rail"><div><p className="eyebrow">Ve a cualquier estación</p><h2>Misiones cortas</h2></div>{stations.map((s,i)=><button key={s.id} onClick={()=>select(s.id)} className={progress.missions.includes(s.id)?'mission-done':''}><span className="station-index" style={{background:s.color}}>{progress.missions.includes(s.id)?'✓':i+1}</span><span><strong>{s.name}</strong><small>{s.note}</small></span>{s.id==='band'&&!unlocked&&<span aria-label="Band room locked">◇</span>}</button>)}<p>Each mission adds 25 XP once. Discoveries add 5 XP once. Explore freely; no countdown.</p></aside></div>}
 {view==='guide'&&<Guide progress={progress}/>}{view==='quiz'&&<Quiz progress={progress} update={update} speak={speak} canSpeak={canSpeak}/>}
 <footer className="spanish-footer"><span>{ready?'Progress stays on this browser. No account or recording.':'Loading your progress…'}</span><button className="text-button" onClick={()=>setReset(true)}>Reset Spanish progress</button></footer></main>
 {selection&&<StationDialog key={selection.id} stationId={selection.id} item={selection.item} progress={progress} update={update} close={()=>setSelection(null)} speak={speak} canSpeak={canSpeak}/>}{reset&&<dialog ref={resetRef} className="reset-dialog" onCancel={()=>setReset(false)} aria-labelledby="reset-title"><h2 id="reset-title">Start Spanish again?</h2><p>This resets discoveries, missions and Spanish quiz results in this browser. Ecology progress stays saved.</p><button className="primary" onClick={()=>{try{window.localStorage.removeItem(STORAGE_KEY)}catch{}setProgress(emptyProgress());setReset(false)}}>Reset Spanish</button><button onClick={()=>setReset(false)}>Keep my progress</button></dialog>}
 <StationLink onSelect={select} view={view} ready={ready}/></div>;
}
function StationLink({onSelect,view,ready}:{onSelect:(s:string)=>void;view:string;ready:boolean}){const used=useRef(false);useEffect(()=>{if(!ready||view!=='adventure'||used.current)return;used.current=true;const station=new URLSearchParams(window.location.search).get('station');if(stations.some(s=>s.id===station))onSelect(station!)},[onSelect,view,ready]);return null;}
