'use client';
import {useEffect,useRef,useState} from 'react';
import {lessons,completeTechniqueIds,visualMemory,fastReviewQuestions,mixedQuestions,challengeQuestions,finalQuestions,type Lesson,type Question,type ConceptId,type TechniqueId} from './content';
import {STORAGE_KEY,emptyProgress,parseProgress,award,finishLesson,addResult,correctAnswer,latestFinal,masteredConcepts,reviewConcepts,type Progress,type Evidence,type RoundMode,type RoundResult} from './learning';
import './rikki.css';

type View='home'|'lesson'|'round'|'results';
type Screen={kind:'learn'|'example'|'detail'|'quick'|'memory'|'done';title?:string;text?:string};
const screensFor=(lesson:Lesson):Screen[]=>lesson.status==='pending'?[{kind:'learn'}]:[{kind:'learn'},{kind:'example'},...(lesson.details??[]).map(d=>({kind:'detail' as const,...d})),{kind:'quick'},{kind:'memory'},{kind:'done'}];
const modeTitle:Record<RoundMode,string>={review:'2-Minute Review',mixed:'Mix It Up',challenge:'Challenge Mode',final:'Final Challenge',targeted:'Targeted Practice'};
const topic=(id:ConceptId)=>lessons.find(l=>l.id===id)!;

function MemoryVisual({lesson,detail}:{lesson:Lesson;detail?:string}){
 const[revealed,setRevealed]=useState(false);
 const visual=visualMemory[lesson.id];
 if(detail)return <div className="rk-diagram"><strong>{detail}</strong></div>;
 return <div className="rk-diagram"><span className="rk-diagram-label">{visual.label}</span>{visual.headline&&<strong>{visual.headline}</strong>}{visual.cards&&<div className={lesson.visual==='senses'?'rk-senses':'rk-diagram-pair'}>{visual.cards.map(card=><span key={card}>{card}</span>)}</div>}{visual.note&&<p>{visual.note}</p>}{visual.reveal&&<><button className="rk-plain" onClick={()=>setRevealed(!revealed)} aria-expanded={revealed}>{revealed?'Hide the connection':'Reveal the connection'}</button>{revealed&&<p>{visual.reveal}</p>}</>}</div>;
}

export default function RikkiApp(){
 const[progress,setProgress]=useState<Progress>(emptyProgress);
 const[ready,setReady]=useState(false);const[storageOK,setStorageOK]=useState(true);
 const[view,setView]=useState<View>('home');const[lessonId,setLessonId]=useState<ConceptId>('point-of-view');const[step,setStep]=useState(0);
 const[questions,setQuestions]=useState<Question[]>([]);const[mode,setMode]=useState<RoundMode>('review');const[index,setIndex]=useState(0);
 const[selected,setSelected]=useState<string[]>([]);const[feedback,setFeedback]=useState<'right'|'wrong'|null>(null);
 const[evidence,setEvidence]=useState<Evidence[]>([]);const[result,setResult]=useState<RoundResult|null>(null);
 const[resetOpen,setResetOpen]=useState(false);const heading=useRef<HTMLHeadingElement>(null);const feedbackRef=useRef<HTMLDivElement>(null);const resetDialog=useRef<HTMLDialogElement>(null);const resetButton=useRef<HTMLButtonElement>(null);
 const lock=useRef(false);const nextLocked=useRef(false);const answerHistory=useRef<Evidence[]>([]);const attempts=useRef(0);const firstCorrect=useRef<boolean|null>(null);
 const currentLesson=topic(lessonId);const screens=screensFor(currentLesson);const screen=screens[Math.min(step,screens.length-1)];
 const question=view==='round'?questions[index]:view==='lesson'&&screen?.kind==='quick'?currentLesson.quickCheck:view==='lesson'&&screen?.kind==='memory'?currentLesson.memoryCheck:null;
 const final=latestFinal(progress);const masters=final?masteredConcepts(final):[];
 useEffect(()=>{try{setProgress(parseProgress(localStorage.getItem(STORAGE_KEY)));}catch{setStorageOK(false);}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));}catch{setStorageOK(false);}},[progress,ready]);
 useEffect(()=>{nextLocked.current=false;if(ready)heading.current?.focus();},[view,step,index,ready,lessonId]);
 useEffect(()=>{if(feedback)feedbackRef.current?.focus();},[feedback]);
 useEffect(()=>{if(resetOpen)resetDialog.current?.showModal();else if(resetDialog.current?.open)resetDialog.current.close();},[resetOpen]);
 function clearAnswer(){lock.current=false;attempts.current=0;firstCorrect.current=null;setSelected([]);setFeedback(null);}
 function goHome(){setView('home');clearAnswer();}
 function startLesson(id:ConceptId,resume=false){const lesson=topic(id);const target=resume&&progress.current?.lessonId===id?Math.min(progress.current.step,screensFor(lesson).length-1):0;setLessonId(id);setStep(target);setView('lesson');setProgress(p=>({...p,current:{lessonId:id,step:target}}));clearAnswer();}
 function advanceLesson(){const next=step+1;setStep(next);clearAnswer();setProgress(p=>({...p,current:{lessonId,step:next}}));}
 function startRound(nextMode:RoundMode,technique?:TechniqueId){let bank:Question[]=[];
  if(nextMode==='review')bank=fastReviewQuestions;
  if(nextMode==='mixed')bank=mixedQuestions;
  if(nextMode==='challenge')bank=challengeQuestions;
  if(nextMode==='final')bank=finalQuestions;
  if(nextMode==='targeted'&&technique)bank=[...mixedQuestions,...finalQuestions].filter(q=>q.conceptId===technique).slice(0,3);
  if(!bank.length)return;setQuestions(bank);setMode(nextMode);setIndex(0);setEvidence([]);answerHistory.current=[];setView('round');clearAnswer();
 }
 function answer(ids:string[]){if(!question||lock.current)return;lock.current=true;attempts.current+=1;const right=correctAnswer(question,ids);if(firstCorrect.current===null)firstCorrect.current=right;setSelected(ids);setFeedback(right?'right':'wrong');
  if(right){setProgress(p=>award(p,question.id));if(view==='round'){const entry:Evidence={questionId:question.id,conceptId:question.conceptId,firstCorrect:firstCorrect.current,attempts:attempts.current};answerHistory.current=[...answerHistory.current,entry];setEvidence(answerHistory.current);}}
 }
 function retry(){lock.current=false;setSelected([]);setFeedback(null);heading.current?.focus();}
 // Runs only from the Continue button; the timestamp identifies a completed round.
 // eslint-disable-next-line react-hooks/purity
 function nextQuestion(){if(nextLocked.current)return;nextLocked.current=true;if(view==='lesson'){advanceLesson();return;}if(index+1<questions.length){setIndex(index+1);clearAnswer();return;}const next:RoundResult={id:`${Date.now()}-${mode}`,mode,evidence:answerHistory.current};setResult(next);setProgress(p=>addResult(p,next));setView('results');clearAnswer();}
 function finish(){setProgress(p=>finishLesson(p,lessonId));goHome();}
 function confirmReset(){setProgress(emptyProgress());setView('home');setStep(0);clearAnswer();setResult(null);setResetOpen(false);resetButton.current?.focus();}
 const firstWins=evidence.filter(e=>e.firstCorrect).length;

 return <div className="rk-app" data-ready={ready} aria-busy={!ready}>
  <a className="rk-skip" href="#rikki-main">Skip to activity</a>
  <header className="rk-topbar"><a href="/" className="rk-brand"><span aria-hidden="true">Y7</span>Yusuf’s study club</a><a href="/subjects/language-arts/" className="rk-shelf">Language Arts</a><span className="rk-stars" aria-label={`${progress.awards.length} stars earned`}>★ {progress.awards.length}</span></header>
  <main id="rikki-main" className="rk-main">
   {view==='home'?<>
    <div className="rk-title-row"><div><p className="rk-kicker">STORY TECHNIQUES · ONE CHALLENGE AT A TIME</p><h1 ref={heading} tabIndex={-1}>Rikki-Tikki-Tavi <span>Study Adventure</span></h1></div><div className="rk-progress"><strong>{progress.completed.length}/{completeTechniqueIds.length} concepts completed</strong><progress value={progress.completed.length} max={completeTechniqueIds.length} aria-label="Completed concepts"/><div className="rk-trail" aria-label="Concept progress">{lessons.filter(l=>l.status==='complete').map(l=><span key={l.id} className={progress.completed.includes(l.id as TechniqueId)?'rk-trail-done':''} aria-label={`${l.title}: ${progress.completed.includes(l.id as TechniqueId)?'complete':'to explore'}`}>{l.icon}</span>)}</div>{final&&<span>{masters.length}/{completeTechniqueIds.length} mastered in your latest final challenge</span>}</div></div>
    <div className="rk-adventure"><figure className="rk-garden"><img src="/quizzes/rikki-tikki-tavi/garden-adventure.webp" width="1536" height="1024" alt="An alert mongoose watches a cobra partly hidden in a sunlit garden while a tailorbird perches above."/><figcaption>Beautiful garden. Hidden danger. Look for the author’s choices.</figcaption></figure><section className="rk-picker" aria-labelledby="topics-title"><div className="rk-section-head"><h2 id="topics-title">Choose a technique</h2><span>Short rounds · no timer</span></div><div className="rk-topic-grid">{lessons.map((l,i)=><button key={l.id} className={`rk-topic rk-color-${i} ${progress.completed.includes(l.id as TechniqueId)?'rk-complete':''}`} onClick={()=>startLesson(l.id)} disabled={!ready}><span className="rk-icon" aria-hidden="true">{l.icon}</span><span><strong>{l.title}</strong><small>{l.status==='pending'?'More coming soon':progress.completed.includes(l.id as TechniqueId)?'✓ Completed · revisit anytime':visualMemory[l.id].label}</small></span></button>)}</div>{progress.current&&<button className="rk-resume" onClick={()=>startLesson(progress.current!.lessonId,true)}>Resume {topic(progress.current.lessonId).title}</button>}</section></div>
    <section className="rk-mode-grid" aria-label="Practice modes"><button onClick={()=>startRound('review')} disabled={!ready}><span>⚡</span><strong>2-Minute Review</strong><small>8 memory hooks · at your pace</small></button><button onClick={()=>startRound('mixed')} disabled={!ready}><span>↔</span><strong>Mix It Up</strong><small>Match a story example to a technique</small></button><button onClick={()=>startRound('final')} disabled={!ready}><span>★</span><strong>Final Challenge</strong><small>10 questions · find what to review</small></button><button onClick={()=>startRound('challenge')} disabled={!ready}><span>✦</span><strong>Challenge Mode</strong><small>Explore how techniques work together</small></button></section>
    {progress.needsReview.length>0&&<section className="rk-home-review"><h2>Your next small win</h2><div>{progress.needsReview.map(id=><button className="rk-plain" key={id} onClick={()=>startRound('targeted',id)}>{topic(id).icon} Practice {topic(id).title}</button>)}</div></section>}
   </>:<>
    <div className="rk-activity-bar"><button className="rk-plain" onClick={goHome}>All topics</button><span>{view==='lesson'?`${currentLesson.icon} ${currentLesson.title}`:view==='results'?modeTitle[result?.mode??mode]:modeTitle[mode]}</span><span>{view==='lesson'&&currentLesson.status==='complete'?`${Math.min(step+1,screens.length)}/${screens.length}`:view==='round'?`${index+1}/${questions.length}`:''}</span></div>
    <section className={`rk-stage ${view==='lesson'&&!question?'rk-story-stage':''}`} data-technique={question?.conceptId??lessonId}>
     {view==='lesson'&&screen.kind==='learn'&&<><p className="rk-kicker">{currentLesson.status==='pending'?'INTRODUCTION ONLY':'LEARN · ONE IDEA'}</p><h1 ref={heading} tabIndex={-1}>{currentLesson.icon} {visualMemory[currentLesson.id].label}</h1><p className="rk-explanation">{currentLesson.explanation}</p><MemoryVisual lesson={currentLesson}/>{currentLesson.status==='pending'?<><p className="rk-pending">{currentLesson.pendingMessage}</p><button className="rk-primary" onClick={goHome}>Back to complete topics</button></>:<button className="rk-primary" onClick={advanceLesson}>See a story example</button>}</>}
     {view==='lesson'&&screen.kind==='example'&&<><p className="rk-kicker">{currentLesson.exampleLabel}</p><h1 ref={heading} tabIndex={-1}>Spot {currentLesson.title.toLowerCase()}</h1><div className="rk-example"><span aria-hidden="true">{currentLesson.icon}</span><p>{currentLesson.example}</p></div>{currentLesson.id==='imagery'&&<img className="rk-example-art" src="/quizzes/rikki-tikki-tavi/garden-adventure.webp" width="1536" height="1024" alt="Lush colorful plants surround an alert mongoose and a partly hidden cobra."/>}<button className="rk-primary" onClick={advanceLesson}>{currentLesson.details?.length?'Explore the next idea':'Try a quick check'}</button></>}
     {view==='lesson'&&screen.kind==='detail'&&<><p className="rk-kicker">ONE MORE CONNECTION</p><h1 ref={heading} tabIndex={-1}>{screen.title}</h1><p className="rk-explanation">{screen.text}</p><MemoryVisual key={step} lesson={currentLesson} detail={currentLesson.details?.find(d=>d.title===screen.title)?.memoryHook}/><button className="rk-primary" onClick={advanceLesson}>{screens[step+1]?.kind==='quick'?'Try a quick check':'Next small idea'}</button></>}
     {view==='lesson'&&screen.kind==='done'&&<><p className="rk-kicker">CONCEPT COMPLETE</p><h1 ref={heading} tabIndex={-1}>✓ {currentLesson.title}</h1><p className="rk-explanation">{currentLesson.memoryHook}</p><p className="rk-support">You connected the idea to the story. Revisit it whenever you like.</p><button className="rk-primary" onClick={finish}>Save and choose the next topic</button></>}
     {question&&<><p className="rk-kicker">{view==='round'?`${topic(question.conceptId).icon} ${mode==='final'?'FINAL CHALLENGE':modeTitle[mode]}`:screen.kind==='memory'?'MEMORY CHALLENGE':'QUICK CHECK'}</p><h1 ref={heading} tabIndex={-1}>{question.prompt}</h1><p className="rk-source">{question.sourceLabel}</p>{question.mode==='multiple'&&<p className="rk-support">This example uses more than one technique. Select all that apply, then check.</p>}<div className="rk-options" role={question.mode==='multiple'?'group':undefined} aria-label="Answer choices">{question.options.map((option,i)=>question.mode==='multiple'?<label className={`rk-option ${selected.includes(option.id)?'rk-selected':''}`} key={option.id}><input type="checkbox" checked={selected.includes(option.id)} disabled={!!feedback} onChange={e=>setSelected(ids=>e.target.checked?[...ids,option.id]:ids.filter(id=>id!==option.id))}/><span>{option.text}</span></label>:<button key={option.id} disabled={!!feedback} className={`rk-option ${selected.includes(option.id)?'rk-selected':''}`} onClick={()=>answer([option.id])}><span className="rk-option-letter" aria-hidden="true">{String.fromCharCode(65+i)}</span>{option.text}</button>)}</div>{question.mode==='multiple'&&!feedback&&<button className="rk-primary" disabled={!selected.length} onClick={()=>answer(selected)}>Check my choices</button>}{feedback&&<div ref={feedbackRef} tabIndex={-1} className={`rk-feedback rk-${feedback}`} role="status"><strong>{feedback==='right'?'✓ You’ve got it.':'Not quite. Try another angle.'}</strong><p>{feedback==='right'?question.feedback:question.hint}</p><button className="rk-primary" onClick={feedback==='right'?nextQuestion:retry}>{feedback==='right'?(view==='round'&&index+1===questions.length?'See my results':'Continue'):'Try again'}</button></div>}{view==='round'&&!feedback&&<p className="rk-round-note">One question at a time. You can retry every answer.</p>}</>}
     {view==='results'&&result&&<><p className="rk-kicker">ROUND COMPLETE · {modeTitle[result.mode]}</p><h1 ref={heading} tabIndex={-1}>{result.mode==='final'?`You mastered ${masteredConcepts(result).length} of ${completeTechniqueIds.length} techniques.`:'Nice work. Keep the ideas connected.'}</h1><p className="rk-explanation">{result.evidence.filter(e=>e.firstCorrect).length}/{result.evidence.length} correct on your first try. You worked through every question.</p>{result.mode==='final'?<>{reviewConcepts(result).length?<section className="rk-targets"><h2>Only these need another look</h2>{reviewConcepts(result).map(id=><button key={id} className="rk-plain" onClick={()=>startRound('targeted',id)}>{topic(id).icon} Practice {topic(id).title}</button>)}</section>:<p className="rk-success-line">All techniques connected. You can keep exploring!</p>}</>:result.mode==='challenge'?<p className="rk-support">Combined questions can use several techniques. Revisit any topic to explore their connections.</p>:<section className="rk-targets">{[...new Set(result.evidence.filter(e=>!e.firstCorrect&&e.conceptId!=='characterization').map(e=>e.conceptId as TechniqueId))].map(id=><button key={id} className="rk-plain" onClick={()=>startRound('targeted',id)}>{topic(id).icon} Practice {topic(id).title}</button>)}</section>}<button className="rk-primary" onClick={goHome}>Choose my next adventure</button></>}
    </section>
    {view==='round'&&<div className="rk-round-progress"><progress value={index+(feedback==='right'?1:0)} max={questions.length} aria-label="Round progress"/><span>{firstWins} first-try wins · retries always welcome</span></div>}
   </>}
  </main>
  <div className="rk-footer"><span>{storageOK?'Progress saves on this browser. No account needed.':'Saving is unavailable in this browser. You can still play this session.'}</span><button className="rk-text-button" ref={resetButton} onClick={()=>setResetOpen(true)}>Reset Rikki progress</button></div>
  <dialog className="rk-reset" ref={resetDialog} onCancel={()=>setResetOpen(false)} onClose={()=>{setResetOpen(false);resetButton.current?.focus();}} aria-labelledby="reset-title"><h2 id="reset-title">Reset this adventure?</h2><p>This clears Rikki lessons, stars, and quiz results on this browser.</p><div><button className="rk-primary" onClick={()=>setResetOpen(false)}>Keep my progress</button><button className="rk-plain" onClick={confirmReset}>Reset Rikki progress</button></div></dialog>
 </div>;
}
