'use strict';
const data=window.ECOLOGY;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const missions=[['foundations','Living systems','Life, habitats, and the levels of organization.','◎','#81dec1'],['energy','Follow the energy','Food webs, energy pyramids, and nature’s recyclers.','↗','#d3fa6d'],['relationships','Better together?','Competition, predators, and symbiotic partnerships.','✧','#ffb777'],['cycles','Nature on repeat','Water, carbon, oxygen, and nitrogen in motion.','↻','#c4b2ff']];
const key='yusuf-ecology-v1';
let saved={mastered:[],missed:[],attempts:0,correct:0,labs:[],sound:false};
try{const v=JSON.parse(localStorage.getItem(key)||'null');if(v&&Array.isArray(v.mastered)&&Array.isArray(v.missed)){saved={...saved,...v};saved.mastered=saved.mastered.filter(id=>data.questions.some(q=>q.id===id));saved.missed=saved.missed.filter(id=>data.questions.some(q=>q.id===id));if(!Array.isArray(saved.labs))saved.labs=[];}}catch{}
let activeView='base',run=null,lab='chain',chain=[],order=[],relationIndex=0,cycle='water',guideMode='cards',audioContext,toastTimer;
const shuffled=arr=>{const a=[...arr];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function save(){try{localStorage.setItem(key,JSON.stringify(saved));}catch{toast('Browser storage is unavailable. Your progress will last for this visit.');}updateRail();}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3300);}
function ding(ok=true){if(!saved.sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);osc.type='sine';osc.frequency.setValueAtTime(ok?523:220,audioContext.currentTime);osc.frequency.exponentialRampToValueAtTime(ok?784:196,audioContext.currentTime+.16);gain.gain.setValueAtTime(.055,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.3);osc.start();osc.stop(audioContext.currentTime+.32);}catch{}}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const d=document.createElement('div');d.className='confetti';d.setAttribute('aria-hidden','true');d.innerHTML=Array.from({length:27},(_,i)=>`<i style="left:${i*3.7}%;animation-delay:${(i%7)*.07}s"></i>`).join('');document.body.append(d);setTimeout(()=>d.remove(),3000);}
function updateRail(){let n=saved.mastered.length,p=Math.round(n/data.questions.length*100);$('rank').textContent=p===100?'Ecosystem expert':p>=75?'Forest guardian':p>=50?'Trail scientist':p>=25?'Field researcher':'Curious explorer';$('mastery-bar').style.width=p+'%';$('mastery-label').textContent=`${n} / ${data.questions.length} mastered`;const b=$('sound');b.textContent=saved.sound?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(saved.sound));b.setAttribute('aria-label',saved.sound?'Turn sound off':'Turn sound on');}
function show(view,focus=true){activeView=view;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!=='view-'+view);document.querySelectorAll('.nav').forEach(b=>{let on=b.dataset.view===view;b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(view==='base')renderBase();if(view==='lab')renderLab();if(view==='guide')renderGuide();if(view==='progress')renderProgress();if(focus){$('main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
function renderBase(){ $('practice-invite').innerHTML=saved.missed.length?practiceCard(saved.missed.length,false):''; $('missions').innerHTML=missions.map((m,i)=>{let qs=data.questions.filter(q=>q.topic===m[0]),n=qs.filter(q=>saved.mastered.includes(q.id)).length;return `<button class="mission" data-mission="${m[0]}" style="--accent:${m[4]}"><div class="mission-top"><span class="mission-glyph" aria-hidden="true">${m[3]}</span><span class="mission-number">MISSION 0${i+1}</span></div><h3>${m[1]}</h3><p>${m[2]}</p><span class="mission-end">${qs.length} questions · ${n} mastered <span aria-hidden="true">↗</span></span></button>`;}).join('');}
function startQuiz(topic='all',ids=null,practiceContext={}){let qs=ids?[...new Set(ids)].map(id=>data.questions.find(q=>q.id===id)).filter(Boolean):topic==='all'||topic==='mix'?data.questions:data.questions.filter(q=>q.topic===topic);if(!qs.length){toast('Nothing to retry. Your trail is clear!');return;}if(topic==='mix')qs=missions.flatMap(m=>shuffled(data.questions.filter(q=>q.topic===m[0])).slice(0,5));let title=ids?'Practice missed questions':topic==='all'?'Master Quiz':topic==='mix'?'The mixed challenge':missions.find(m=>m[0]===topic)[1];run={title,practice:ids!==null,practiceRound:practiceContext.round||1,originalResult:practiceContext.originalResult||null,questions:shuffled(qs).map(q=>({...q,choices:shuffled(q.options.map((text,index)=>({text,index})))})),index:0,selected:null,checked:false,hint:false,answers:[],streak:0,best:0};show('quiz');renderQuestion();}
function practiceMissed(){
  const ids=run.answers.filter(a=>!a.correct).map(a=>a.id);
  const originalResult=run.practice?run.originalResult:{title:run.title,correct:run.answers.filter(a=>a.correct).length,total:run.questions.length};
  startQuiz('all',ids,{originalResult,round:run.practice?run.practiceRound+1:1});
}
function originalGradeMarkup(){
  const original=run.originalResult;
  return original?`<p class="original-grade"><span>Original ${esc(original.title)} grade</span><strong>${original.correct}/${original.total} · ${Math.round(100*original.correct/original.total)}/100</strong><span>Practice keeps this grade unchanged.</span></p>`:'';
}
function practiceCard(count,fromResults){
  return `<section class="practice-next"><img src="forest-ecosystem.png" width="1536" height="1024" alt="A forest ecosystem with animals and a winding river"><div><span class="overline">${fromResults?'YOUR NEXT STEP':'READY WHEN YOU ARE'}</span><h2>${count} ${count===1?'question':'questions'} to practice</h2><p>${fromResults?'Try the questions you just missed in a separate round.':'Your missed questions are saved on this device.'} Same visuals, reshuffled answers. Questions you get right leave the practice list.</p><button class="primary" id="${fromResults?'retry-run':'practice-saved'}">Practice ${count} missed ${count===1?'question':'questions'} ↗</button>${fromResults?'<p class="practice-small">Your original quiz grade stays unchanged. You can also practice later from Base camp.</p>':''}</div></section>`;
}
function currentGrade(){const answered=run.answers.length,correct=run.answers.filter(a=>a.correct).length;return {answered,correct,revealed:answered>=10,score:answered?Math.round(100*correct/answered):null};}
function gradeMarkup(g){return `<div class="grade-heading"><span class="overline">${g.revealed?(run.practice?'THIS PRACTICE ROUND':'YOUR GRADE SO FAR'):'FIRST, FIND YOUR RHYTHM'}</span><span id="grade-note">${g.revealed?'Based on your answers so far · rounded to the nearest point':run.questions.length<10?'Your grade will appear when this short round is complete.':`Your score unlocks after 10 answers. ${g.answered}/10 answered.`}</span></div><div class="grade-numbers" ${g.revealed?'':'hidden'}><div><strong id="run-score">${g.revealed?`${g.correct}/${g.answered}`:''}</strong><span>correct</span></div><div class="grade-total"><strong id="run-grade">${g.revealed?`${g.score}/100`:''}</strong><span>grade out of 100</span></div></div>`;}
function updateGrade(){const g=currentGrade();document.querySelector('.live-grade').innerHTML=gradeMarkup(g);const progress=document.querySelector('.quiz-progress');progress.setAttribute('aria-valuenow',String(g.answered));progress.querySelector('span').style.width=g.answered/run.questions.length*100+'%';}
function renderQuestion(){let q=run.questions[run.index],m=missions.find(m=>m[0]===q.topic);let total=run.questions.length,g=currentGrade();
$('view-quiz').innerHTML=`<div class="quiz-head"><div><span class="overline">${m[1].toUpperCase()}</span><h1>${run.title}</h1></div><button class="quiet" data-view="base">← Base camp</button></div>${run.practice?`<div class="practice-context"><span class="chip">Practice round ${run.practiceRound}</span><p>Only missed questions. Each correct answer clears one from your practice list.</p>${originalGradeMarkup()}</div>`:''}<section class="live-grade" aria-label="Current quiz grade" aria-live="polite" aria-atomic="true">${gradeMarkup(g)}</section><div class="quiz-progress" role="progressbar" aria-label="Quiz progress" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${run.index}"><span style="width:${run.index/total*100}%"></span></div><div class="quiz-layout"><section class="question-box" aria-labelledby="question-title"><span class="question-number">QUESTION ${run.index+1} OF ${total}</span><h2 id="question-title" tabindex="-1">${esc(q.prompt)}</h2>${window.ecologyVisual(q)}<div class="choices" role="group" aria-label="Answer choices">${q.choices.map((o,i)=>`<button class="answer" data-answer="${i}" aria-pressed="false"><span class="key" aria-hidden="true">${i+1}</span><span>${esc(o.text)}</span><span class="answer-mark"></span></button>`).join('')}</div><div id="hint" class="hint" hidden></div><div id="feedback" class="feedback" role="status" hidden></div><div class="question-actions"><button class="hint-button" id="hint-button">Need a thinking tip?</button><button class="primary" id="check-answer" disabled>Check answer</button><button class="primary" id="next-question" hidden>${run.index===total-1?'See my results':'Next discovery'} →</button></div></section><aside class="run-aside"><div class="panel"><span class="overline">YOUR FIELD NOTES</span><h3>Keep making connections.</h3><p id="streak">${run.streak>1?run.streak+' correct in a row. Keep connecting the dots!':'Take your time. Think it through.'}</p></div><img class="art" src="forest-ecosystem.png" alt="A forest ecosystem with animals, plants, and a river"><div class="panel"><span class="overline">A GOOD SCIENTIST</span><p>Uses mistakes as clues. Missed questions come back for another try.</p><p style="font-size:12px">Keyboard: 1–4 to choose. Enter to check or continue.</p></div></aside></div>`;
}
function choose(i){if(!run||run.checked)return;run.selected=i;document.querySelectorAll('.answer').forEach((b,j)=>{b.classList.toggle('selected',j===i);b.setAttribute('aria-pressed',String(j===i));});$('check-answer').disabled=false;}
function check(){if(!run||run.checked||run.selected===null)return;run.checked=true;let q=run.questions[run.index],chosen=q.choices[run.selected],ok=chosen.index===q.answer;run.answers.push({id:q.id,correct:ok,chosen:chosen.text});run.streak=ok?run.streak+1:0;run.best=Math.max(run.best,run.streak);saved.attempts++;if(ok){saved.correct++;if(!saved.mastered.includes(q.id)){saved.mastered.push(q.id);if([18,36,54,72].includes(saved.mastered.length))toast('New ranger level unlocked!');}saved.missed=saved.missed.filter(id=>id!==q.id);}else if(!saved.missed.includes(q.id))saved.missed.push(q.id);save();ding(ok);document.querySelectorAll('.answer').forEach((b,i)=>{b.disabled=true;b.classList.remove('selected');if(q.choices[i].index===q.answer){b.classList.add('correct');b.querySelector('.answer-mark').textContent='✓ Correct';}else if(i===run.selected){b.classList.add('wrong');b.querySelector('.answer-mark').textContent='Your pick';}});$('feedback').hidden=false;$('feedback').classList.toggle('is-wrong',!ok);$('feedback').innerHTML=`<strong>${ok?'That’s a discovery!':'A useful clue for next time.'}</strong>${esc(q.explanation)}${!ok?'<p class="practice-feedback">Saved for your follow-up practice round.</p>':run.practice?'<p class="practice-feedback">Cleared from your practice list.</p>':''}`;$('check-answer').hidden=true;$('next-question').hidden=false;$('hint-button').hidden=true;updateGrade();$('streak').textContent=run.streak>1?`${run.streak} correct in a row. Nice connections!`:ok?'One more connection made.':'You’ll get another chance in the retry round.';$('next-question').focus({preventScroll:true});}
function next(){if(!run||!run.checked)return;if(++run.index>=run.questions.length){renderResults();return;}run.selected=null;run.checked=false;run.hint=false;renderQuestion();$('question-title').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function renderResults(){
  const right=run.answers.filter(a=>a.correct).length,wrong=run.answers.filter(a=>!a.correct),pct=Math.round(100*right/run.questions.length);
  const title=run.practice?(wrong.length?'More connections made, Yusuf.':'Every missed question, cleared.'):(pct>=80?'Brilliant exploring, Yusuf.':'You’re building your science brain.');
  const message=run.practice?(wrong.length?'The next practice round brings back only the questions you still missed.':'You’ve answered every question in this practice set correctly. Nice work sticking with it!'):(wrong.length?'Your quiz is complete. Now give the tricky questions another try.':'Every connection found. Ready to explore another trail?');
  $('view-quiz').innerHTML=`<section class="results"><span class="result-medal" aria-hidden="true">✧</span><p class="overline">${run.practice?`PRACTICE ROUND ${run.practiceRound} COMPLETE`:'EXPEDITION LOG COMPLETE'}</p><h1>${title}</h1><p class="lead" style="margin:auto">${message}</p><div class="stat-grid"><div class="stat"><strong>${right}/${run.questions.length}</strong><span>${run.practice?'Correct in practice':'Correct this round'}</span></div><div class="stat"><strong>${pct}/100</strong><span>${run.practice?'Practice grade':'Final quiz grade'}</span></div><div class="stat"><strong>${run.best}</strong><span>Best answer streak</span></div></div>${originalGradeMarkup()}${wrong.length?practiceCard(wrong.length,true):run.practice?'<div class="practice-complete">Practice set complete. All of these questions have left your practice list.</div>':'<div class="lab-note">Perfect round! Your completed questions count toward your ranger level.</div>'}<div class="result-actions"><button class="secondary" data-view="base">${wrong.length?'Practice later · Base camp':'Back to base camp'}</button><button class="quiet" data-view="lab">Try a discovery lab</button></div>${wrong.length?`<h2 style="font-size:24px;text-align:left;margin-top:38px">Your clues for next time</h2><div class="review-list">${wrong.map(a=>{let q=data.questions.find(q=>q.id===a.id);return `<details><summary>${esc(q.prompt)}</summary><p>Your answer: ${esc(a.chosen)}</p><p><strong>Correct answer: ${esc(q.options[q.answer])}</strong><br>${esc(q.explanation)}</p></details>`;}).join('')}</div>`:''}</section>`;
  if(pct>=80)celebrate();window.scrollTo({top:0,behavior:'instant'});
}
function tip(){const q=run.questions[run.index];let tips={foundations:'Look for what is living, what is nonliving, and how many kinds of organisms are included. For levels, zoom from one organism outward.',energy:'Trace energy from food to eater. Producers capture energy; consumers eat. At each new feeding level, about one-tenth remains.',relationships:'Ask who benefits, who is harmed, and whether anyone is unaffected. For populations, consider food supply and survival.',cycles:'Follow the material. Think about whether it is moving into air, into a living thing, into water, or back into soil.'};$('hint').textContent=tips[q.topic];$('hint').hidden=false;run.hint=true;}
function completeLab(id){if(!saved.labs.includes(id)){saved.labs.push(id);save();toast('Discovery stamp earned!');ding();}}
const labItems=[['chain','Food-chain builder'],['pyramid','Energy pyramid'],['levels','Life, zoomed out'],['cycles','Cycle explorer'],['relations','Relationship detective']];
function renderLab(){ $('view-lab').innerHTML=`<span class="overline">TOUCH. TEST. UNDERSTAND.</span><h1 class="page-title">Discovery lab.</h1><p class="lead">Try an idea and see what happens. These models help you explain the science in your own words.</p><div class="pill-row" aria-label="Choose a lab">${labItems.map(m=>`<button class="pill ${lab===m[0]?'active':''}" data-lab="${m[0]}" aria-pressed="${lab===m[0]}">${m[1]}</button>`).join('')}</div><section class="panel lab-surface" id="lab-body"></section>`;if(lab==='chain')renderChain();if(lab==='pyramid')renderPyramid();if(lab==='levels')renderLevels();if(lab==='cycles')renderCycles();if(lab==='relations')renderRelations();}
const chainCorrect=['Grass','Grasshopper','Mouse','Hawk'];
const chainBank=['Hawk','Mouse','Grass','Grasshopper'];
function renderChain(){let labels=['Producer','Primary consumer','Secondary consumer','Tertiary consumer'];$('lab-body').innerHTML=`<div class="lab-top"><div><span class="overline">MODEL 01 · ENERGY MOVES ONE WAY</span><h2>Build a four-level food chain.</h2><p>In this example, the grasshopper eats grass, the mouse eats the grasshopper, and the hawk eats the mouse. Tap the organisms in the order energy travels.</p></div><span class="chip">3 consumers</span></div><div class="step-slots">${labels.map((label,i)=>`${i?'<span class="flow-arrow" aria-hidden="true">→</span>':''}<div class="slot ${chain[i]?'filled':''}"><strong>${chain[i]||'?'}</strong><span>${label}</span></div>`).join('')}</div><div class="tile-bank">${chainBank.map(t=>`<button class="tile" data-chain="${t}" ${chain.includes(t)?'disabled':''}>${t}</button>`).join('')}</div><div class="lab-actions"><button class="primary" id="check-chain" ${chain.length!==4?'disabled':''}>Test my chain</button><button class="secondary" id="undo-chain" ${!chain.length?'disabled':''}>Undo last</button><button class="quiet" id="reset-chain">Clear chain</button></div><div class="lab-note">The Sun supplies the energy. Grass is the <strong>first organism</strong> in the chain. An arrow means “energy passes to,” so it points from food to eater.</div><div id="lab-feedback" class="lab-note" role="status" hidden></div><details class="source-web"><summary>Connect this to the study-guide food web</summary><p>The original picture gives organisms but no completed arrows. Using these feeding facts, connect grass → grasshopper → mouse → hawk. A shorter example is grass → rabbit → fox, where the fox eats the rabbit.</p><img src="study-food-web.jpg" alt="Original study-guide forest food web: trees and plants, grass, grasshopper, rabbit, mouse, squirrel, deer, fox, hawk-like raptor, and wolf-like predator. The worksheet has no arrows."><p>Worksheet illustration: Sheri Amsel, ExploringNature.org. This practice chain supplies feeding facts; it does not claim that every animal always has one diet.</p></details>`;}
function labFeedback(text,ok=false){$('lab-feedback').hidden=false;$('lab-feedback').textContent=text;ding(ok);}
function renderPyramid(){ $('lab-body').innerHTML=`<div class="lab-top"><div><span class="overline">MODEL 02 · FOLLOW THE TEN PERCENT</span><h2>Where does the energy go?</h2><p>Change the energy stored in producers. Watch how much is available at each consumer level in this simplified 10% model.</p></div></div><div class="pyramid-layout"><div class="pyramid" role="img" aria-label="Energy pyramid showing producers at the bottom and three consumer levels above">${[['Tertiary consumers',34,'#b9afff'],['Secondary consumers',54,'#8ccecd'],['Primary consumers',76,'#9bd791'],['Producers',100,'#d3fa6d']].map((x,i)=>`<div class="pyramid-tier" style="width:${x[1]}%;background:${x[2]}"><small>${x[0]}</small><strong id="energy-${3-i}"></strong></div>`).join('')}</div><div class="range-box"><label for="producer-energy">Energy in producers</label><output id="energy-output" for="producer-energy">10,000 energy units</output><input type="range" id="producer-energy" min="1000" max="20000" step="1000" value="10000"><p>Each step up receives about <strong>10%</strong> of the previous level’s stored energy. This is an estimate, not an exact rule for every ecosystem.</p></div></div><div class="lab-note"><strong>The other ~90%?</strong> Organisms use energy for life processes and release much of it as heat. Some energy remains in uneaten or undigested material. Energy flows; matter cycles.</div><div class="lab-question"><h3>If producers hold 10,000 units, how much reaches tertiary consumers?</h3><div class="lab-answers">${['1,000 units','100 units','10 units','9,000 units'].map((t,i)=>`<button class="lab-answer" data-pyramid-answer="${i}">${t}</button>`).join('')}</div></div><div id="lab-feedback" class="lab-note" role="status" hidden></div>`;updatePyramid(10000);}
function updatePyramid(n){$('energy-output').textContent=n.toLocaleString()+' energy units';for(let i=0;i<4;i++)$('energy-'+i).textContent=(n/10**i).toLocaleString(undefined,{maximumFractionDigits:2})+' units';}
const levels=['Organism','Population','Community','Ecosystem','Biome','Biosphere'];
const levelExamples=['One deer','Deer of one species in one area','All living populations in that area','The community + nonliving surroundings','A large region with a characteristic climate and life','All Earth’s ecosystems'];
function renderLevels(){ $('lab-body').innerHTML=`<span class="overline">MODEL 03 · FROM ONE LIFE TO ALL LIFE</span><h2>Zoom out, one level at a time.</h2><p class="lead">Tap the six levels from smallest to largest. Watch a single deer become part of a much bigger story.</p><div class="level-ladder">${levels.map((l,i)=>`<div class="level-row ${order[i]?'filled':''}"><span class="level-num">0${i+1}</span><div><strong>${order[i]||'Choose the next level'}</strong><small>${order[i]?levelExamples[levels.indexOf(order[i])]:'…'}</small></div>${order[i]?'<span aria-hidden="true">↗</span>':''}</div>`).join('')}</div><div class="tile-bank">${['Biome','Population','Biosphere','Organism','Ecosystem','Community'].map(l=>`<button class="tile" data-level="${l}" ${order.includes(l)?'disabled':''}>${l}</button>`).join('')}</div><div class="lab-actions"><button class="primary" id="check-levels" ${order.length!==6?'disabled':''}>Check the zoom</button><button class="secondary" id="undo-level" ${!order.length?'disabled':''}>Undo last</button><button class="quiet" id="reset-levels">Clear levels</button></div><div id="lab-feedback" class="lab-note" role="status" hidden></div>`;}
const cycles={
water:{name:'Water',subtitle:'A raindrop’s round trip',nodes:[['Evaporation','Sunlight heats liquid water; it becomes water vapor.'],['Condensation','Water vapor cools into liquid droplets in clouds.'],['Precipitation','Water falls as rain, snow, sleet, or hail.'],['Collection','Water collects in lakes and oceans, flows as runoff, or enters soil.']],note:'There is no single starting point. Plants add another pathway: transpiration releases water vapor through their leaves. Water can take many different routes.',prompt:'Water vapor leaves the leaves of a tree. What is happening?',options:['Condensation','Transpiration','Precipitation','Nitrogen fixation'],answer:1,explain:'Transpiration is the release of water vapor from plants, mostly through leaf openings called stomata.'},
carbon:{name:'Carbon',subtitle:'Carbon goes from air to life and back',nodes:[['Air','Carbon dioxide is present in the atmosphere.'],['Photosynthesis','Plants take in CO₂ and use light to build sugars.'],['Feeding','Carbon in food passes to animals that eat plants or other animals.'],['Return','Respiration and decomposition return carbon to the environment.']],note:'Burning fuels also releases carbon dioxide. Carbon atoms are reused; energy must keep entering ecosystems. Plants and animals both perform respiration.',prompt:'How does photosynthesis affect carbon dioxide in the air?',options:['It changes nitrogen into carbon.','It destroys carbon atoms.','It takes in CO₂ to build sugars.','It only releases CO₂.'],answer:2,explain:'Photosynthesis removes carbon dioxide from the air and stores its carbon in sugars. Those carbon atoms can later move through food webs.'},
oxygen:{name:'Oxygen',subtitle:'Two processes, connected',nodes:[['Photosynthesis','Plants use light, water, and CO₂ to make sugar.'],['Oxygen released','Photosynthesis releases oxygen into water or air.'],['Aerobic respiration','Plants and animals use oxygen to release energy from food.'],['CO₂ + water','Respiration produces carbon dioxide and water, which can be used in photosynthesis.']],note:'Plants do both photosynthesis and respiration. Respiration happens in cells; it is not simply the act of breathing. Matter cycles between organisms and their surroundings.',prompt:'Which statement correctly connects plants and animals?',options:['Plants photosynthesize and also respire.','Only animals use oxygen.','Plants make oxygen by eating animals.','Respiration removes all oxygen permanently.'],answer:0,explain:'Plants produce oxygen during photosynthesis and use oxygen during aerobic respiration. Animals also respire and release carbon dioxide.'},
nitrogen:{name:'Nitrogen',subtitle:'The tiny microbes with a huge job',nodes:[['Fixation','Certain bacteria convert atmospheric N₂ into ammonia or ammonium.'],['Soil → plants','Other bacteria make nitrates; plants absorb usable nitrogen through roots.'],['Food + recycling','Animals get nitrogen by eating. Decomposers recycle nitrogen from wastes and dead matter.'],['Back to air','Denitrifying bacteria return nitrogen gas to the atmosphere.']],note:'Different bacteria perform different jobs. Most plants and animals cannot use nitrogen gas directly. Nitrogen is needed for proteins and DNA; the Sun is not the nitrogen source.',prompt:'What do nitrogen-fixing bacteria do?',options:['Turn oxygen into sugar.','Eat all the nitrogen in the air.','Make plants breathe N₂ directly.','Convert N₂ into compounds organisms can use.'],answer:3,explain:'Nitrogen-fixing bacteria change atmospheric nitrogen gas into ammonia/ammonium, making nitrogen available to living systems.'}
};
function renderCycles(){let c=cycles[cycle];$('lab-body').innerHTML=`<span class="overline">MODEL 04 · MATTER GOES ROUND</span><h2>${c.subtitle}</h2><div class="pill-row" aria-label="Choose a cycle">${Object.entries(cycles).map(([id,c])=>`<button class="pill ${cycle===id?'active':''}" data-cycle="${id}" aria-pressed="${cycle===id}">${c.name} cycle</button>`).join('')}</div><p class="lead">Read the path from left to right. The final stage connects back to the first.</p><div class="cycle-diagram">${c.nodes.map((n,i)=>`<article class="cycle-node"><span class="number">0${i+1} ${i===3?'↻':'→'}</span><strong>${n[0]}</strong>${n[1]}</article>`).join('')}</div><div class="lab-note">${c.note}</div><div class="lab-question"><h3>${c.prompt}</h3><div class="lab-answers">${c.options.map((o,i)=>`<button class="lab-answer" data-cycle-answer="${i}">${o}</button>`).join('')}</div></div><div id="lab-feedback" class="lab-note" role="status" hidden></div>`;}
const relationshipCases=[{text:'A bee gets nectar while moving pollen between flowers, helping the flowers reproduce.',answer:'Mutualism',explain:'The bee gains food and the flowers gain pollination. Both benefit: + / +.'},{text:'A tick drinks a deer’s blood. The tick gets food while the deer loses blood and may be harmed.',answer:'Parasitism',explain:'The tick benefits and the deer is harmed: + / −.'},{text:'A bird nests in a tree. In this example, the bird gains shelter and the tree is neither helped nor harmed.',answer:'Commensalism',explain:'One benefits and the other is unaffected: + / 0.'},{text:'Two deer need the same limited patch of grass.',answer:'Competition',explain:'They compete for a limited resource. Competition can happen within one species or between species.'},{text:'Wolves hunt together to catch a large prey animal.',answer:'Cooperation',explain:'The wolves work together. Cooperation can improve survival, feeding, or defense.'},{text:'An owl catches and eats a mouse.',answer:'Predation',explain:'The owl is the predator; the mouse is its prey. Predation differs from a long-term symbiotic partnership.'}];
function renderRelations(){let c=relationshipCases[relationIndex];$('lab-body').innerHTML=`<span class="overline">MODEL 05 · WHO GETS WHAT?</span><h2>Crack the relationship code.</h2><div class="relations-grid">${[['Mutualism','+ / +','Both organisms benefit.'],['Commensalism','+ / 0','One benefits; the other is unaffected.'],['Parasitism','+ / −','One benefits; the other is harmed.']].map(x=>`<article class="relation"><div class="signs">${x[1]}</div><h3>${x[0]}</h3><p>${x[2]}</p></article>`).join('')}</div><p style="color:var(--muted);font-size:13px;margin-top:14px">Key: + benefits · − harmed · 0 unaffected. Species can be written in either order.</p><div class="lab-question"><span class="overline">CASE ${relationIndex+1} OF ${relationshipCases.length}</span><h3 style="margin-top:15px">${c.text}</h3><div class="lab-answers">${['Mutualism','Commensalism','Parasitism','Competition','Cooperation','Predation'].map(o=>`<button class="lab-answer" data-relation="${o}">${o}</button>`).join('')}</div></div><div id="lab-feedback" class="lab-note" role="status" hidden></div><button class="secondary" id="next-case" style="margin-top:20px" hidden>${relationIndex===5?'Start cases again':'Next case'} →</button>`;}
function renderGuide(){ $('view-guide').innerHTML=`<span class="overline">EVERY TERM. EVERY BIG IDEA.</span><h1 class="page-title">Your field guide.</h1><p class="lead">${data.coverage.sourceVocabularyCount} study-guide terms + ${data.coverage.supplementalTerms.length} helpful extras. Tap a card to reveal its meaning and an example.</p><div class="pill-row"><button class="pill ${guideMode==='cards'?'active':''}" data-guide="cards" aria-pressed="${guideMode==='cards'}">Vocabulary cards</button><button class="pill ${guideMode==='notes'?'active':''}" data-guide="notes" aria-pressed="${guideMode==='notes'}">Study-guide walkthrough</button></div><div id="guide-content"></div>`;if(guideMode==='cards'){$('guide-content').innerHTML='<label class="search-label" for="term-search">Find a term or idea</label><input id="term-search" class="search" type="search" placeholder="Try: photosynthesis, energy, predator…"><p id="term-count" style="font-size:13px;color:var(--muted);margin-top:12px" role="status"></p><div id="glossary" class="glossary"></div>';renderCards('');}else{$('guide-content').innerHTML=`<div class="coverage-note"><strong>A note for your class:</strong> The guide asks for six characteristics of life but doesn’t list them. This review groups them as cells, DNA/heredity, growth and development, energy use, response/homeostasis, and reproduction. Your teacher may group them differently. The “two types” of predator–prey relationships prompt is also unclear; review predation, population effects, competition, and cooperation here, and check the wording in your class notes.</div><div class="notes-grid">${data.notes.map(n=>`<article class="panel study-note"><span class="overline">${missions.find(m=>m[0]===n.topic)[1]}</span><h3 style="margin-top:15px">${esc(n.title)}</h3><p>${esc(n.body)}</p></article>`).join('')}</div><details class="source-links"><summary>Study material and science references</summary><p>Based on “Unit 1 Major: Ecology Part 1 — Study Guide: On level.” Every vocabulary term and question topic is covered. This review provides explanations; the original guide contains blank answer spaces.</p>${data.sources.map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a></p>`).join('')}</details>`;}}
function renderCards(query){const qs=query.trim().toLowerCase();const terms=data.glossary.map((g,i)=>({...g,i})).filter(g=>(g.term+' '+g.definition+' '+g.example).toLowerCase().includes(qs));$('term-count').textContent=`${terms.length} of ${data.glossary.length} cards`;$('glossary').innerHTML=terms.length?terms.map(g=>`<button class="flashcard" data-flip="${g.i}" aria-pressed="false"><span class="overline">FIELD CARD ${String(g.i+1).padStart(2,'0')}</span><strong class="term">${esc(g.term)}</strong><span class="flip-label">Tap to discover ↗</span></button>`).join(''):'<p class="lead">No matching cards. Try a shorter word.</p>';}
function renderProgress(){let n=saved.mastered.length,pct=Math.round(n/data.questions.length*100);$('view-progress').innerHTML=`<span class="overline">YOUR CURIOSITY, COLLECTED</span><h1 class="page-title">My expedition.</h1><p class="lead">A question counts as mastered after you answer it correctly. Progress is saved in this browser on this device.</p><div class="stat-grid"><div class="stat"><strong>${n}/${data.questions.length}</strong><span>Questions mastered</span></div><div class="stat"><strong>${saved.attempts?Math.round(saved.correct/saved.attempts*100):0}%</strong><span>All-time accuracy</span></div><div class="stat"><strong>${saved.labs.length}/8</strong><span>Discovery stamps</span></div></div><div class="badges">${[['◎','Field researcher',25],['✧','Trail scientist',50],['♧','Forest guardian',75],['☆','Ecosystem expert',100]].map(b=>`<article class="badge ${pct>=b[2]?'earned':''}"><span class="symbol" aria-hidden="true">${b[0]}</span><strong>${b[1]}</strong><small>${pct>=b[2]?'Earned!':b[2]+'% of questions mastered'}</small></article>`).join('')}</div><h2 style="font-size:25px;margin-top:33px">Your four trails</h2><div class="topic-progress">${missions.map(m=>{let qs=data.questions.filter(q=>q.topic===m[0]),count=qs.filter(q=>saved.mastered.includes(q.id)).length;return `<article><strong>${m[1]}</strong><div class="meter"><span style="width:${count/qs.length*100}%"></span></div><span>${count} / ${qs.length}</span></article>`;}).join('')}</div><div class="lab-note"><strong>Discovery stamps:</strong> ${saved.labs.length?saved.labs.map(l=>({'chain':'Food chain','levels':'Organization levels','pyramid':'Energy pyramid','relations':'Relationship cases','water':'Water cycle','carbon':'Carbon cycle','oxygen':'Oxygen cycle','nitrogen':'Nitrogen cycle'}[l])).join(' · '):'Explore the labs to start collecting.'}</div><div class="result-actions" style="justify-content:start">${saved.missed.length?`<button class="primary" id="retry-all">Practice ${saved.missed.length} missed questions ↗</button>`:'<button class="primary" id="new-mix">Try a mixed challenge ↗</button>'}<button class="secondary" data-view="lab">Collect discovery stamps</button></div><button class="reset" id="reset-progress">Reset this device’s ecology progress</button>`;}
function labAnswer(button,ok,explain,stamp,selector){document.querySelectorAll(selector).forEach(b=>b.disabled=true);button.classList.add(ok?'right':'wrong');labFeedback((ok?'Yes! ':'Keep this clue: ')+explain,ok);if(ok&&stamp)completeLab(stamp);if(!ok){const retry=document.createElement('button');retry.className='secondary';retry.textContent='Try this lab again';retry.style.marginTop='16px';retry.addEventListener('click',renderLab);$('lab-feedback').append(document.createElement('br'),retry);}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.view){show(b.dataset.view);return;}if(b.dataset.mission){startQuiz(b.dataset.mission);return;}
if(b.dataset.answer!==undefined){choose(Number(b.dataset.answer));return;}
if(b.dataset.lab){lab=b.dataset.lab;renderLab();return;}if(b.dataset.cycle){cycle=b.dataset.cycle;renderCycles();return;}
if(b.dataset.chain){chain.push(b.dataset.chain);renderChain();return;}if(b.dataset.level){order.push(b.dataset.level);renderLevels();return;}
if(b.dataset.guide){guideMode=b.dataset.guide;renderGuide();return;}
if(b.dataset.flip!==undefined){const g=data.glossary[Number(b.dataset.flip)],on=b.getAttribute('aria-pressed')==='true';b.setAttribute('aria-pressed',String(!on));b.classList.toggle('flipped',!on);b.innerHTML=on?`<span class="overline">FIELD CARD ${String(Number(b.dataset.flip)+1).padStart(2,'0')}</span><strong class="term">${esc(g.term)}</strong><span class="flip-label">Tap to discover ↗</span>`:`<strong style="font-family:var(--display);margin-bottom:12px;color:var(--mint)">${esc(g.term)}</strong><span class="definition">${esc(g.definition)}</span><span class="example">${esc(g.example)}</span><span class="flip-label">↶ Back to term</span>`;return;}
if(b.dataset.cycleAnswer!==undefined){let c=cycles[cycle];labAnswer(b,Number(b.dataset.cycleAnswer)===c.answer,c.explain,cycle,'[data-cycle-answer]');return;}
if(b.dataset.pyramidAnswer!==undefined){labAnswer(b,b.dataset.pyramidAnswer==='2','10,000 → 1,000 → 100 → 10. Tertiary consumers are three steps above producers.','pyramid','[data-pyramid-answer]');return;}
if(b.dataset.relation){let c=relationshipCases[relationIndex],ok=b.dataset.relation===c.answer;labAnswer(b,ok,c.explain,null,'[data-relation]');if(ok){if(!saved.relationCases)saved.relationCases=[];if(!saved.relationCases.includes(relationIndex))saved.relationCases.push(relationIndex);save();if(saved.relationCases.length===6)completeLab('relations');}$('next-case').hidden=false;return;}
switch(b.id){case'start-master':case'start-all':startQuiz('all');break;case'quick-quiz':case'new-mix':startQuiz('mix');break;case'check-answer':check();break;case'next-question':next();break;case'hint-button':tip();break;case'retry-run':practiceMissed();break;case'practice-saved':case'retry-all':startQuiz('all',[...saved.missed]);break;case'sound':saved.sound=!saved.sound;save();if(saved.sound)ding();break;case'check-chain':{const ok=chain.every((x,i)=>x===chainCorrect[i]);labFeedback(ok?'Connected! Grass → grasshopper → mouse → hawk. The three consumers are primary, secondary, and tertiary, in that order.':'Follow the feeding facts above. Energy begins in grass, then passes to the grasshopper, mouse, and hawk. Clear or undo a tile and try again.',ok);if(ok)completeLab('chain');break;}case'undo-chain':chain.pop();renderChain();break;case'reset-chain':chain=[];renderChain();break;case'check-levels':{const ok=order.every((x,i)=>x===levels[i]);labFeedback(ok?'You’ve zoomed all the way out: organism → population → community → ecosystem → biome → biosphere.':'Look at the group sizes: one organism; one species in an area; all living populations; living + nonliving; climate region; all life on Earth. Clear or undo and try again.',ok);if(ok)completeLab('levels');break;}case'undo-level':order.pop();renderLevels();break;case'reset-levels':order=[];renderLevels();break;case'next-case':relationIndex=(relationIndex+1)%relationshipCases.length;renderRelations();break;case'reset-progress':if(confirm('Reset only your ecology quiz progress, badges, and discovery stamps on this device?')){saved={mastered:[],missed:[],attempts:0,correct:0,labs:[],sound:saved.sound};save();renderProgress();toast('A fresh expedition is ready.');}break;}
});
document.addEventListener('input',e=>{if(e.target.id==='term-search')renderCards(e.target.value);if(e.target.id==='producer-energy')updatePyramid(Number(e.target.value));});
document.addEventListener('keydown',e=>{if(activeView!=='quiz'||!run||run.index>=run.questions.length||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(/^[1-4]$/.test(e.key)&&!run.checked){e.preventDefault();choose(Number(e.key)-1);}if(e.key==='Enter'&&e.target.tagName!=='BUTTON'){e.preventDefault();run.checked?next():check();}});
updateRail();renderBase();
if(new URLSearchParams(location.search).get('quiz')==='master')startQuiz('all');
